import { temelYBSDersleri } from "./temelybs";

export const akdenizYbs = [
  // ================= AKDENİZ BÖLGESİ =================
  {
    id: 59,
    universite: "Akdeniz Üniversitesi",
    fakulte: "Uygulamalı Bilimler Fakültesi",
    fakulte_adresi:
      "Akdeniz Üniversitesi Kampüsü, Dumlupınar Bulvarı, 07058 Konyaaltı/Antalya",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YBS 151 - Bilişim Sistemleri ve Teknolojilerine Giriş",
        "YBS 153 - Algoritma ve Programlamaya Giriş",
        "YBS 155 - Matematik",
        "YBS 157 - Pazarlama İlkeleri",
        "YBS 159 - İktisada Giriş I",
        "TDB 101 - Türk Dili I",
        "ATA 101 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "YBD 101 - İngilizce I",
        "KPD 101 - Kariyer Planlama",
        "YBS 152 - Yönetim ve Organizasyon",
        "YBS 154 - İleri Düzey Ofis Uygulamaları",
        "YBS 156 - Bilgisayar Donanımı ve İşletim Sistemleri",
        "YBS 158 - Veri Yapıları ve Algoritmalar",
        "YBS 160 - İktisada Giriş II",
        "TBD 102 - Türk Dili II",
        "ATA 102 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "YBD 102 - İngilizce II",
      ],
      grade_2: [
        "YBS 251 - Nesne Yönelimli Programlama - 1",
        "YBS 253 - Web Tabanlı Programlama - 1",
        "YBS 255 - Veritabanına Giriş",
        "YBS 257 - Proje Yönetimi",
        "YBS 259 - Örgütsel Davranış",
        "YBS 261 - İstatistik I",
        "YBS 263 - Uygulamalı Girişimcilik",
        "YBS 265 - Genel Muhasebe I",
        "YBS 252 - Nesne Yönelimli Programlama - 2",
        "YBS 254 - Web Tabanlı Programlama - 2",
        "YBS 256 - Veritabanı Yönetim Sistemleri",
        "YBS 258 - Bilimsel Araştırma Yöntemleri",
        "YBS 260 - Üretim Yönetimi",
        "YBS 262 - İstatistik II",
        "YBS 264 - Sistem Analizi ve Tasarımı",
        "YBS 266 - Genel Muhasebe II",
      ],
      grade_3: [
        "YBS 351 - Veri İletişimi ve Bilgisayar Ağları",
        "YBS 353 - Mobil Uygulama Geliştirme",
        "YBS 355 - Grafik ve Bilişim Arayüz Tasarımı",
        "YBS 357 - Yöneylem Araştırması I",
        "TDP 301 - Toplumsal Duyarlılık ve Katkı",
        "YBS 361 - Karar Verme Teknikleri",
        "YBS 352 - Bilgi Sistemleri Entegrasyonu",
        "YBS 354 - Yapay Zekâ ve Makine Öğrenmesi",
        "YBS 356 - İnsan Kaynakları Yönetimi",
        "YBS 358 - Yöneylem Araştırması II",
        "YBS 360 - Sistem Yönetimi ve Güvenliği",
        "YBS 362 - Finansal Yönetim",
      ],
      grade_4: [
        "YBS 451 - Kurumsal Kaynak Planlama",
        "YBS 453 - Yönetim Bilişim Sistemlerinde Güncel Konular",
        "YBS 483 - Uygulamalı Veri Madenciliği (Seçmeli)",
        "YBS 485 - Derin Öğrenme (Seçmeli)",
        "YBS 495 - Robotik Uygulamaları (Seçmeli)",
        "YBS 402 - İş Yerinde Eğitim (Full Semester Internship)",
      ],
    },
  },
  {
    id: 60,
    universite: "Antalya Belek Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi: "Kadriye Mah. Celal Bayar Cad. No:5-6, 07525 Serik/Antalya",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YBS 101 - Yönetim Bilişim Sistemleri I",
        "YBS 103 - Temel Bilgi Teknolojileri",
        "YBS 105 - İktisada Giriş",
        "YBS 107 - Hukukun Temel Kavramları",
        "YBS 109 - İşletme Matematiği I",
        "ATA 101 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "TUR 101 - Türk Dili I",
        "ING 101 - İngilizce I",
        "YBS 102 - Yönetim Bilişim Sistemleri II",
        "YBS 104 - Algoritma ve Programlamaya Giriş",
        "YBS 106 - İşletme Bilimine Giriş",
        "YBS 108 - Bilişim Hukuku",
        "YBS 110 - İşletme Matematiği II",
        "ATA 102 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "TUR 102 - Türk Dili II",
        "ING 102 - İngilizce II",
        "KRP 102 - Kariyer Planlama",
      ],
      grade_2: [
        "YBS 201 - Temel Programlama",
        "YBS 203 - İleri Ofis Uygulamaları",
        "YBS 205 - Grafik ve Canlandırma",
        "YBS 207 - Yönetim ve Organizasyon",
        "YBS 209 - İş Sağlığı ve Güvenliği",
        "YBS 202 - Veri Tabanı Yönetim Sistemleri",
        "YBS 204 - Web Tasarımı",
        "YBS 206 - Üretim Yönetimi",
        "YBS 208 - İstatistik",
        "YBS 210 - Finansal Muhasebe",
        "Seçmeli Ders I",
        "Seçmeli Ders II",
      ],
      grade_3: [
        "YBS 301 - İnternet Tabanlı Programlama",
        "YBS 303 - Bilgisayar Ağları ve Güvenlik",
        "YBS 305 - Kurumsal Kaynak Planlaması",
        "YBS 307 - Sistem Analizi ve Tasarımı",
        "YBS 309 - Pazarlama",
        "YBS 302 - Mobil Programlama",
        "YBS 304 - İş Zekâsı Ve Veri Madenciliği",
        "YBS 306 - İşletme Finansı",
        "YBS 308 - Yöneylem Araştırması",
        "YBS 310 - Staj",
        "Seçmeli Ders III",
        "Seçmeli Ders IV",
      ],
      grade_4: [
        "YBS 401 - Mobil Uygulama Geliştirme",
        "YBS 403 - Karar Destek Sistemleri",
        "YBS 405 - Yapay Zeka",
        "YBS 407 - İnsan Kaynakları Yönetimi",
        "YBS 409 - Müşteri İlişkileri Yönetimi",
        "YBS 411 - Kullanıcı Deneyimi Tasarımı (Seçmeli)",
        "YBS 413 - İşletme Analitiği (Seçmeli)",
        "YBS 402 - Mezuniyet Projesi",
        "YBS 404 - İş yeri Uygulaması (Full Semester)",
      ],
    },
  },
  {
    id: 61,
    universite: "Alanya Üniversitesi",
    fakulte: "Sanat ve Tasarım Fakültesi", // Not: YBS bazen Sanat Tasarım altında olabiliyor bazı vakıflarda veya İİSBF
    fakulte_adresi: "Cikcilli Mah. Saraybeleni Cad. No:7, 07400 Alanya/Antalya",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YBS 101 - Bilişim Hukuku",
        "YBS 103 - Matematik",
        "YBS 105 - Yönetim Bilişim Sistemleri",
        "YBS 107 - İşletme Yönetimine Giriş",
        "SEC 101 - Seçmeli Ders 1 (Üniversite Seçmeli)",
        "ING 111 - Genel İngilizce I",
        "TKL 111 - Türk Dili I",
        "YBS 102 - Nesne Tabanlı Programlama",
        "YBS 104 - Genel Ekonomi",
        "YBS 106 - İstatistik",
        "YBS 108 - Bilgisayar Donanımı ve İşletim Sistemleri",
        "SEC 102 - Seçmeli Ders 2 (Üniversite Seçmeli)",
        "TKL 112 - Türk Dili II",
        "ING 112 - Genel İngilizce II",
      ],
      grade_2: [
        "YBS 201 - Veri Yapıları ve Algoritmalar",
        "YBS 203 - İnsan Kaynakları Yönetimi",
        "YBS 205 - Optimizasyon Teknikleri",
        "YBS 207 - Genel Muhasebe",
        "SEC 201 - Seçmeli Ders 3 (Üniversite Seçmeli)",
        "HIST 211 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "YBS 200 - Yaz Stajı I",
        "YBS 202 - Veri Tabanı Yönetimi ve Modellemesi",
        "YBS 204 - Finansal Yönetim",
        "YBS 206 - Karar Destek Sistemleri",
        "YBS 208 - Web Tasarımı ve İnternet Programlama",
        "SEC 202 - Seçmeli Ders 4 (Üniversite Seçmeli)",
        "HIST 212 - Atatürk İlkeleri ve İnkılap Tarihi II",
      ],
      grade_3: [
        "YBS 301 - Kurumsal Kaynak Planlama",
        "YBS 303 - Yöneylem Araştırması",
        "YBS 305 - Stratejik Yönetim",
        "YBS 307 - Yapay Zeka ve Makine Öğrenmesi",
        "SEC 301 - Seçmeli Ders 5 (Bölüm Seçmeli)",
        "SEC 303 - Seçmeli Ders 6 (Bölüm Seçmeli)",
        "YBS 300 - Yaz Stajı II",
        "YBS 302 - Araştırma Yöntemleri",
        "YBS 304 - Proje Yönetimi",
        "YBS 306 - Bilgisayar Ağları ve Güvenliği",
        "SEC 302 - Seçmeli Ders 7 (Bölüm Seçmeli)",
        "SEC 304 - Seçmeli Ders 8 (Bölüm Seçmeli)",
      ],
      grade_4: [
        "YBS 401 - Lisans Projesi",
        "YBS 403 - Dijital Pazarlama",
        "YBS 405 - Mobil Uygulama Geliştirme",
        "SEC 401 - Seçmeli Ders 9 (Bölüm Seçmeli)",
        "SEC 403 - Seçmeli Ders 10 (Bölüm Seçmeli)",
        "SEC 405 - Seçmeli Ders 11 (Bölüm Seçmeli)",
        "YBS 400 - Yönetim Bilişim Sistemleri Uygulamaları",
        "YBS 402 - Bulut Bilişim",
        "SEC 402 - Seçmeli Ders 12 (Bölüm Seçmeli)",
        "SEC 404 - Seçmeli Ders 13 (Bölüm Seçmeli)",
        "SEC 406 - Seçmeli Ders 14 (Bölüm Seçmeli)",
      ],
    },
  },
  {
    id: 62,
    universite: "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi: "Balcalı Mah. Çatalan Cad. No:201/1, 01250 Sarıçam/Adana",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 63,
    universite: "Hatay Mustafa Kemal Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Tayfur Sökmen Kampüsü, 31060 Alahan/Antakya/Hatay",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "1407101 - Yönetim Bilişim Sistemlerine Giriş",
        "1407103 - Temel Bilgi Teknolojileri",
        "1407105 - Matematik I",
        "1407107 - İktisada Giriş",
        "1407109 - İşletme Yönetimine Giriş",
        "1407141 - Türk Dili I",
        "1407151 - Atatürk İlkeleri ve İnk. Tarihi I",
        "1407131 - Yabancı Dil I",
        "1407199 - Kariyer Planlama",
        "1407202 - Grafik ve Animasyon",
        "1407204 - Bilgisayar Donanımı",
        "1407206 - Matematik II",
        "1407208 - Hukuka Giriş",
        "Muhasebe İlkeleri",
        "1407242 - Türk Dili II",
        "1407252 - Atatürk İlkeleri ve İnk. Tarihi II",
        "1407232 - Yabancı Dil II",
      ],
      grade_2: [
        "1407301 - Algoritma ve Programlama I",
        "1407303 - Veri Tabanı Yönetim Sistemleri I",
        "1407305 - Açık Kaynak İşletim Sistemi",
        "1407307 - Yönetim ve Organizasyon",
        "1407309 - İstatistik",
        "1407311 - İşletme Finansı",
        "Seçmeli Ders I (3. Yarıyıl)",
        "1407402 - Algoritma ve Programlama II",
        "1407404 - Veri Tabanı Yönetim Sistemleri II",
        "1407406 - Bilgisayar Ağları ve İletişim",
        "1407408 - Sistem Analizi ve Tasarımı",
        "1407410 - İstatistik II",
        "1407412 - Finansal Yönetim",
        "Seçmeli Ders II (4. Yarıyıl)",
      ],
      grade_3: [
        "1407501 - Internet Tabanlı Programlama",
        "1407503 - Veri Madenciliği",
        "1407505 - Sunucu Yönetimi",
        "1407507 - Pazarlama İlkeleri",
        "Seçmeli Ders Grubu I (5. Yarıyıl)",
        "1407602 - Bilgi Güvenliği",
        "Elektronik İşletme Yönetimi",
        "1407606 - Karar Destek Sistemleri",
        "Nesne Tabanlı Programlama",
        "Seçmeli Ders Grubu II (6. Yarıyıl)",
      ],
      grade_4: [
        "1407701 - Yapay Zekâ",
        "1407703 - Mobil Uygulama Geliştirme-I",
        "1407701 - Ağ Yönetimi",
        "1407703 - Üç Boyutlu Tasarım ve Modelleme",
        "Seçmeli Ders Grubu III (7. Yarıyıl)",
        "Kurumsal Bilişim Sistemleri",
        "1407804 - Mobil Uygulama Geliştirme -II",
        "1407806 - Büyük Veri ve İş Analitiği",
        "1407808 - Bitirme Projesi",
        "Seçmeli Ders Grubu IV (8. Yarıyıl)",
      ],
    },
  },
  {
    id: 64,
    universite: "İskenderun Teknik Üniversitesi",
    fakulte: "İşletme ve Yönetim Bilimleri Fakültesi",
    fakulte_adresi: "Merkez Kampüs, 31200 İskenderun/Hatay",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YBS2-1101 - İşletme Bilimine Giriş",
        "YBS2-1103 - Ekonomi-I",
        "YBS2-1105 - Algoritmalara Giriş",
        "YBS2-1107 - Yönetim ve Organizasyon",
        "YBS2-1109 - Matematik-I",
        "TOY2-1101 - Teknoloji Okuryazarlığı",
        "TUR2-1101 - Türk Dili-I",
        "İNG2-1101 - İngilizce-I",
        "AİİT2-1101 - Atatürk İlkeleri ve İnkılap Tarihi-I",
        "YBS2-1202 - Yönetim Bilişim Sistemleri",
        "YBS2-1204 - Ekonomi-II",
        "YBS2-1206 - Programlamaya Giriş",
        "YBS2-1208 - Analitik Yazı ve İletişim Teknikleri",
        "YBS2-1210 - Matematik-II",
        "YOG2-1202 - Yenilikçilik ve Girişimcilik",
        "TUR2-1202 - Türk Dili-II",
        "İNG2-1202 - İngilizce-II",
        "AİİT2-1202 - Atatürk İlkeleri ve İnkılap Tarihi-II",
      ],
      grade_2: [
        "YBS2-2301 - Sistem Analizi ve Tasarımı",
        "YBS2-2303 - İstatistik",
        "YBS2-2305 - Veri Tabanı Yönetim Sistemleri",
        "YBS2-2307 - Görsel Programlama",
        "YBS2-2309 - Üretim Yönetimi",
        "ANG2-2301 - Anayurt Güvenliği",
        "YBS2-2402 - Çağdaş Yönetim Teknikleri",
        "YBS2-2404 - Dijital Pazarlama ve E-Ticaret",
        "YBS2-2406 - Ağ Yönetimi ve Bilgi Güvenliği",
        "YBS2-2408 - Nesne Tabanlı Programlama",
        "YBS2-2410 - Bilişim Projesi Yönetimi",
        "İSG2-2402 - İş Sağlığı ve Güvenliği",
      ],
      grade_3: [
        "YBS2-3501 - Yöneylem Araştırması-I",
        "YBS2-3503 - Veri Madenciliği",
        "ETK2-3501 - Etik",
        "MIS Seçmeli Ders I (5. Yarıyıl)",
        "MIS Seçmeli Ders II (5. Yarıyıl)",
        "MIS Seçmeli Ders III (5. Yarıyıl)",
        "MIS Seçmeli Ders IV (5. Yarıyıl)",
        "YBS2-3602 - Yöneylem Araştırması-II",
        "YBS2-3604 - Web Tasarımı ve İnternet Programlama",
        "ÜEK2-3601 - Üniversite Etkinliklerine Katılım",
        "MIS Seçmeli Ders V (6. Yarıyıl)",
        "MIS Seçmeli Ders VI (6. Yarıyıl)",
        "MIS Seçmeli Ders VII (6. Yarıyıl)",
        "MIS Seçmeli Ders VIII (6. Yarıyıl)",
      ],
      grade_4: [
        "YBS2-4701 - Endüstri 4.0’da Bilişim",
        "YBS2-4703 - Start-up’lar ve Dijital Girişimcilik",
        "GNÇ2-4701 - Gönüllülük Çalışmaları",
        "MIS Seçmeli Ders IX (7. Yarıyıl)",
        "MIS Seçmeli Ders X (7. Yarıyıl)",
        "MIS Seçmeli Ders XI (7. Yarıyıl)",
        "MIS Seçmeli Ders XII (7. Yarıyıl)",
        "Bitirme Projesi Seçmeli Dersi veya İş Dünyası ile Entegrasyon",
        "MIS Seçmeli Ders XIII (8. Yarıyıl)",
        "MIS Seçmeli Ders XIV (8. Yarıyıl)",
        "MIS Seçmeli Ders XV (8. Yarıyıl)",
        "MIS Seçmeli Ders XVI (8. Yarıyıl)",
      ],
    },
  },
  {
    id: 65,
    universite: "Osmaniye Korkut Ata Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Karacaoğlan Yerleşkesi, Fakıuşağı Mah. 80000 Merkez/Osmaniye",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "TBT101 - TEMEL BİLGİ TEKNOLOJİLERİ",
        "YBS103 - MATEMATİK I",
        "YBS105 - EKONOMİ I",
        "YBS107 - GENEL MUHASEBE I",
        "YBS109 - TEMEL HUKUK",
        "TDL101 - TÜRK DİLİ I",
        "YDİ101 - YABANCI DİL: İNGİLİZCE I",
        "DOY101 - DİJİTAL OKURYAZARLIK",
        "YBS102 - YÖNETİM BİLİŞİM SİSTEMLERİNE GİRİŞ",
        "YBS104 - İŞLETME BİLİMİNE GİRİŞ",
        "YBS106 - EKONOMİ II",
        "YBS108 - GENEL MUHASEBE II",
        "YBS110 - MATEMATİK II",
        "TDL102 - TÜRK DİLİ II",
        "YDİ102 - YABANCI DİL: İNGİLİZCE II",
      ],
      grade_2: [
        "YBS201 - ALGORİTMALAR VE PROGRAMLAMAYA GİRİŞ",
        "YBS203 - VERİTABANINA GİRİŞ",
        "YBS205 - BİLİŞİM HUKUKU VE ETİĞİ",
        "YBS207 - YÖNETİM VE ORGANİZASYON",
        "YBS209 - İSTATİSTİK I",
        "YDL201 - MESLEKİ İNGİLİZCE I",
        "ATA101 - ATATÜRK İLKELERİ VE İNKILAP TARİHİ I",
        "YBS202 - PROGRAMLAMA DİLLERİ VE VERİ YAPILARI",
        "YBS204 - VERİTABANI YÖNETİM SİSTEMLERİ",
        "YBS206 - KARAR DESTEK SİSTEMLERİ",
        "YBS208 - PAZARLAMA İLKELERİ",
        "YBS210 - İSTATİSTİK II",
        "YDL202 - MESLEKİ İNGİLİZCE II",
        "ATA102 - ATATÜRK İLKELERİ VE İNKILAP TARİHİ II",
      ],
      grade_3: [
        "YBS301 - ORTA DÜZEYDE PROGRAMLAMA (Java)",
        "YBS303 - İŞLETME FİNANSI",
        "YBS305 - YÖNEYLEM ARAŞTIRMASI I",
        "YBS307 - PAZARLAMA YÖNETİMİ",
        "YBS302 - GÖRSEL PROGRAMLAMA (VB.Net/C#)",
        "YBS304 - PROJE YÖNETİMİ",
        "YBS306 - YÖNEYLEM ARAŞTIRMASI II",
        "YBS308 - LOJİSTİK YÖNETİMİ",
        "Bölüm Seçmelik I (Güz)",
        "Bölüm Seçmelik II (Bahar)",
      ],
      grade_4: [
        "YBS401 - WEB TABANLI PROGRAMLAMA VE TASARIMI",
        "YBS403 - ÜRETİM YÖNETİMİ",
        "YBS405 - BİLİŞİM SİSTEMLERİ YÖNETİMİ",
        "YBS402 - E-İŞ",
        "YBS404 - STRATEJİK YÖNETİM",
        "YBS406 - TEDARİK ZİNCİRİ YÖNETİMİ",
        "Bölüm Seçmelik III (Güz)",
        "Bölüm Seçmelik IV (Bahar)",
      ],
    },
  },
  {
    id: 66,
    universite: "Tarsus Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Tekke Mah. 33400 Tarsus/Mersin",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "OD 107 - Kariyer Planlama",
        "OD 111 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "OD 113 - Türk Dili I",
        "OD 117 - İleri İngilizce I",
        "YB 101 - Algorithms and Programming I",
        "YB 103 - İşletme Matematiği I",
        "YB 105 - Introduction to Microeconomics",
        "YB 107 - Yönetim Bilişim Sistemlerine Giriş",
        "YB 109 - Introduction to Business",
        "OD 112 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "OD 114 - Türk Dili II",
        "OD 118 - İleri İngilizce II",
        "YB 102 - Algorithms and Programming II",
        "YB 104 - İşletme Matematiği II",
        "YB 106 - Introduction to Macroeconomics",
        "YB 108 - Genel Muhasebe",
        "YB 110 - Bilişim Hukuku ve Etiği",
      ],
      grade_2: [
        "YB 201 - Veri Tabanına Giriş",
        "YB 203 - Business Data Communications",
        "YB 205 - Management and Organization",
        "YB 207 - İşletim Sistemleri ve Bilgisayar Donanımı",
        "YB 209 - İstatistik I",
        "YB 211 - İşletme Finansmanı",
        "YB 213 - Academic Writing and Research I",
        "YB 202 - Veri Tabanı Yönetim Sistemleri",
        "YB 204 - Nesneye Yönelik Programlama",
        "YB 206 - Organizational Behaviour",
        "YB 208 - Managerial Communication",
        "YB 210 - İstatistik II",
        "YB 212 - Yönetim Muhasebesi",
        "YB 214 - Academic Writing and Research II",
      ],
      grade_3: [
        "YB 301 - Web Tabanlı Programlama ve Tasarımı",
        "YB 303 - Sistem Analiz ve Tasarımı",
        "YB 305 - Operational Research",
        "YB 307 - Principles of Marketing",
        "Mesleki Seçmeli I (Information/Digital/Network Economics)",
        "Mesleki Seçmeli II (Yatırım Projeleri Analizi/E-Devlet)",
        "YB 302 - Mobil Programlama",
        "YB 304 - Bilgisayar Ağları ve Güvenliği",
        "YB 306 - Business Process Management",
        "YB 308 - Technology and Innovation Management",
        "Mesleki Seçmeli III (Current Issues in MIS/Information Management)",
        "Mesleki Seçmeli IV (Python/R Programming/Data Forecasting)",
      ],
      grade_4: [
        "YB 401 - Veri Madenciliği",
        "YB 403 - Software Management",
        "YB 405 - Dijital Dönüşüm",
        "YB 407 - Decision Support Systems",
        "Mesleki Seçmeli V (Human Resources/Social Networking)",
        "Mesleki Seçmeli VI (Yapay Zeka/Coğrafi Bilgi Sistemleri/Endüstri 4.0)",
        "YB 402 - Kurumsal Kaynak Planlama",
        "YB 404 - IT Project Management",
        "YB 406 - E-Business Management",
        "YB 408 - Bitirme Projesi",
        "Mesleki Seçmeli VII (Cyber Security/Data Science/Deep Learning/Agile)",
        "Mesleki Seçmeli VIII (Stratejik Yönetim/Tedarik Zinciri/CRM)",
      ],
    },
  },
];
