import { temelYBSDersleri } from "./temelybs";

export const ankaraYbs = [
  {
    id: 34,
    universite: "Gazi Üniversitesi",
    fakulte: "Uygulamalı Bilimler Fakültesi",
    fakulte_adresi:
      "Emniyet Mah. Abant 1 Cad. No:10/2C, 06560 Yenimahalle/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "TAR101 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "TUR101 - Türk Dili I",
        "MAT101 - Matematik I",
        "İNG101 - Yabancı Dil I",
        "YBS101 - Genel İşletme",
        "YBS103 - Genel İktisat",
        "YBS105 - Yönetim Bilişim Sistemleri",
        "YBS107 - Bilişim Teknolojileri I",
        "TAR102 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "TUR102 - Türk Dili II",
        "MAT102 - Matematik II",
        "İNG102 - Yabancı Dil II",
        "YBS102 - Girişimcilik",
        "YBS104 - Yönetim ve Organizasyon",
        "YBS106 - Bilişim Teknolojileri II",
        "YBS108 - Algoritma ve Programlamaya Giriş",
      ],
      grade_2: [
        "HUK201 - Hukuk I: Temel Hukuk",
        "MUH201 - Muhasebe I",
        "İST201 - İstatistik I",
        "YBS201 - Çağdaş Yönetim Yaklaşımları",
        "YBS203 - Web Tasarımı",
        "YBS205 - Veritabanı Yönetim Sistemleri",
        "HUK202 - Hukuk II: Bilişim Hukuku",
        "MUH202 - Muhasebe II",
        "İST202 - İstatistik II",
        "YBS202 - Örgütsel Davranış",
        "YBS204 - Görsel Programlama",
        "YBS206 - Nesne Yönelimli Programlama",
        "Seçmeli Ders Grubu (I-II)",
      ],
      grade_3: [
        "BAY301 - Bilimsel Araştırma Yöntemleri",
        "YBS301 - Bilgi Güvenliği ve Etik",
        "YBS303 - Bilgisayar Ağları ve Güvenlik",
        "YBS305 - Web Programlama",
        "YBS307 - Yöneylem Araştırması",
        "YBS302 - E-İşletmecilik Yönetimi",
        "YBS304 - Karar Destek Sistemleri",
        "YBS306 - Tedarik Zinciri Yönetimi",
        "YBS308 - Sistem Analizi ve Tasarımı",
        "YBS310 - Mobil Programlama",
        "Seçmeli Ders Grubu (III-IV)",
      ],
      grade_4: [
        "YBS401 - Mesleki Yabancı Dil I",
        "YBS403 - Kurumsal Kaynak Planlaması",
        "YBS405 - Proje Yönetimi",
        "YBS407 - Güvenli Yazılım Geliştirme",
        "YBS409 - Müşteri İlişkileri Yönetimi",
        "YBS402 - Mesleki Yabancı Dil II",
        "YBS404 - Kurumsal Bilgi Sistemleri",
        "YBS406 - Sosyal Medya",
        "YBS408 - Yapay Zeka Uygulamaları",
        "YBS410 - Bitirme Projesi",
        "Seçmeli Ders Grubu (V-VI)",
      ],
    },
  },
  {
    id: 35,
    universite: "Çankaya Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Merkez Kampüs, Yukarıyurtçu Mah. Mimar Sinan Cad. No:4, 06790 Etimesgut/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "ECON 101 - İktisata Giriş I",
        "CENG 154 - Bilgisayar Programlama I",
        "MATH 111 - İktisat ve Sosyal Bilimler için Matematik I",
        "ENG 121 - Akademik İngilizce I",
        "TURK 101 - Türk Dili I",
        "ESR 103 - Etik İlkeler ve Sosyal Sorumluluk",
        "MIS 101 - Yönetim Bilişim Sistemlerine Giriş",
        "ECON 102 - İktisata Giriş II",
        "MIS 102 - İşletme ve Yönetim Prensipleri",
        "MATH 112 - İktisat ve Sosyal Bilimler için Matematik II",
        "CENG 155 - Bilgisayar Programlama II",
        "ENG 122 - Akademik İngilizce II",
        "TURK 102 - Türk Dili II",
      ],
      grade_2: [
        "Serbest Seçmeli",
        "Teknik Seçmeli I",
        "MAN 209 - YBS için Muhasebe",
        "CENG 241 - Nesneye Yönelik Programlama",
        "STAT 205 - İktisat için İstatistik I",
        "MIS 207 - Veri Bilimi için Programlama",
        "HIST 201 - Atatürk İlke ve İnkilap Tarihi I",
        "Teknik Seçmeli veya MIS Seçmelisi II",
        "MIS 202 - Bilgi ve Yönetim Ekonomisi",
        "MIS 204 - Bilgisayar Ağları",
        "MIS 208 - Veri Analizine Giriş",
        "STAT 206 - İktisat için İstatistik II",
        "HIST 202 - Atatürk İlke ve İnkilap Tarihi II",
      ],
      grade_3: [
        "Seçmeli (MIS) I",
        "MIS 315 - Veri Analitiği I",
        "MIS 303 - Veritabanı Yönetim Sistemleri",
        "MIS 305 - Veri Analizi: Modelleme",
        "MIS 307 - Karar Analizi I",
        "MAN 307 - Pazarlama İlkeleri",
        "Teknik Seçmeli veya MIS Seçmelisi III",
        "MIS 314 - Veri Analitiği II",
        "MIS 306 - Veri Analizi: Tahmin",
        "CENG 382 - Web Programlama",
        "MIS 316 - Sistem Analizi ve Tasarım",
        "MIS 400 - Yaz Stajı",
      ],
      grade_4: [
        "Seçmeli (MIS) II",
        "Seçmeli (MIS) III",
        "Teknik Seçmeli veya MIS Seçmelisi IV",
        "MIS 415 - Kurumsal Uygulamalar",
        "MAN 406 - Proje Yönetimi",
        "MIS 403 - İşletme ve Ekonomi için Makine Öğrenimi",
        "Seçmeli (MIS) IV",
        "Seçmeli (MIS) V",
        "Seçmeli (MIS) VI",
        "Teknik Seçmeli veya MIS Seçmelisi V",
        "MIS 402 - Karar Analizi II",
        "MIS 408 - Mezuniyet Projesi",
      ],
    },
  },
  {
    id: 36,
    universite: "Başkent Üniversitesi",
    fakulte: "Ticari Bilimler Fakültesi",
    fakulte_adresi:
      "Bağlıca Kampüsü, Fatih Sultan Mah. Eskişehir Yolu 18.km, 06790 Etimesgut/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "BTU100 - BİLGİSAYAR OKURYAZARLIĞI",
        "KRY100 - KARİYER PLANLAMA",
        "ORY100 - ÜNİVERSİTE HAYATINA GİRİŞ",
        "İNGL101 - İNGİLİZCE I",
        "TBF111 - EKONOMİYE GİRİŞ I",
        "TBF121 - GENEL MATEMATİK I",
        "TBF141 - HUKUKA GİRİŞ",
        "TÜRK101 - TÜRK DİLİ I",
        "YBS115 - BİLİŞİM SİSTEMLERİ VE TEKNOLOJİLERİNE GİRİŞ",
        "GSBHS - SEÇMELİ GÜZEL SANATLAR/İLK YARDIM",
        "İNGL102 - İNGİLİZCE II",
        "TBF112 - EKONOMİYE GİRİŞ II",
        "TBF122 - GENEL MATEMATİK II",
        "TÜRK102 - TÜRK DİLİ II",
        "YBS112 - İŞLETME YÖNETİMİNE GİRİŞ",
        "YBS116 - ALGORİTMAYA GİRİŞ",
      ],
      grade_2: [
        "ATA201 - ATATÜRK İLKELERİ VE İNKILAP TARİHİ I",
        "İNGL201 - İNGİLİZCE III",
        "TBF211 - MUHASEBE İLKELERİ I",
        "TBF221 - MATEMATİKSEL İSTATİSTİK I",
        "YBS203 - TEKNOLOJİ VE İNOVASYON YÖNTEMİ",
        "YBS215 - YAPISAL PROGRAMLAMA I",
        "ATA202 - ATATÜRK İLKELERİ VE İNKILAP TARİHİ II",
        "İNGL202 - İNGİLİZCE IV",
        "TBF212 - MUHASEBE İLKELERİ II",
        "TBF226 - MATEMATİKSEL İSTATİSTİK II",
        "TBF232 - ÖRGÜTSEL DAVRANIŞ",
        "YBS212 - VERİ TABANI YÖNETİM SİSTEMLERİ",
        "YBS216 - YAPISAL PROGRAMLAMA II",
      ],
      grade_3: [
        "TBF321 - İŞLETME FİNANSI",
        "YBS313 - NESNE YÖNELİMLİ PROGRAMLAMA",
        "YBS343 - İNTERNET BİLGİ SİSTEMLERİ",
        "YBS315 - İNSAN KAYNAKLARI YÖNETİMİ VE BİLGİ SİSTEMLERİ",
        "YBS360 - ZORUNLU YAZ STAJI",
        "YBS364 - WEB UYGULAMALARI TASARIM VE GELİŞTİRME",
        "YBS370 - SİSTEM ANALİZİ VE TASARIMI",
        "Seçimlik Ders I, II, III, IV, V",
      ],
      grade_4: [
        "YBS433 - İNSAN BİLGİSAYAR ETKİLEŞİMİ",
        "YBS471 - YÖNETİM BİLGİ SİSTEMLERİ",
        "YBS450 - İŞLETMEDE MESLEKİ EĞİTİM",
        "Seçimlik Ders VI, VII, VIII, IX, X, XI",
      ],
    },
  },
  {
    id: 37,
    universite: "Ankara Medipol Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi:
      "Hacı Bayram Mah. Talatpaşa Bulvarı No:2, 06050 Altındağ/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "TDL1110139 - TÜRK DİLİ I",
        "YBS1111115 - TEMEL HUKUK",
        "YBS1110141 - İNGİLİZCE I",
        "YBS1111060 - MATEMATİK I",
        "YBS1111033 - YÖNETİM BILIŞİM SİSTEMLERİ",
        "YBS1120070 - İŞLETME VE YÖNETİM İLKELERİ",
        "TDL1210179 - TÜRK DİLİ II",
        "YBS1210188 - İNGİLİZCE II",
        "YBS1211803 - İKTİSADA GİRİŞ",
        "YBS1211814 - MATEMATİK II",
        "YBS1220071 - ALGORİTMA VE PROGRAMLAMAYA GİRİŞ",
        "YBS1220080 - BİLİŞİM TEKNOLOJİLERİ VE SİSTEMLERİ",
      ],
      grade_2: [
        "ATA2110008 - ATATÜRK İLKELERİ VE İNKILAP TARİHİ I",
        "YBS2111660 - MESLEKİ İNGİLİZCE I",
        "YBS2111859 - İSTATİSTİK",
        "YBS2120073 - VERİ ANALİTİĞİNE GİRİŞ",
        "YBS2120075 - YAPISAL PROGRAMLAMA",
        "YBS2120961 - MUHASEBE İLKELERİ",
        "ATA2210184 - ATATÜRK İLKELERİ VE İNKILAP TARİHİ II",
        "YBS2211682 - MESLEKİ İNGİLİZCE II",
        "YBS2211868 - İSTATİKSEL KARAR VERME",
        "YBS2211878 - VERİ TABANINA GİRİŞ",
        "YBS2220077 - FİNANSIN TEMELLERİ",
        "YBS2220964 - NESNE TABANLI PROGRAMLAMA",
      ],
      grade_3: [
        "YBS3112972 - VERİ GÖRSELLEŞTİRME",
        "YBS3180227 - YAZILIM GELİŞTİRME SÜREÇLERİ VE METODOLOJİSİ",
        "YBS3120963 - VERİ ANALİZİ : MADENCİLİK VE MODEL KURMA",
        "YBS3111885 - KURUMSAL KAYNAK PLANLAMA",
        "YBS3280230 - YÖNETİM BILIŞİM SİSTEMLERİ PROJE YÖNETİMİ",
        "YBS3211887 - WEB TABANLI UYGULAMA PROGRAMLAMA",
        "YBS3220083 - İŞLETİM SİSTEMLERİ VE VERİ AĞLARI",
        "YBS3220962 - VERİ ANALİZİ : ÖNGÖRÜ VE TAHMİN",
        "YBS3211896 - İŞ ANALİZİ VE SİSTEM TASARIMI",
      ],
      grade_4: [
        "YBS4180234 - YAZILIM KALİTE YÖNETİMİ",
        "YBS4111956 - MAKİNE ÖĞRENMESİ",
        "YBS4112976 - GİRİŞİMCİLİK, İŞ MODELİ VE İNOVASYON",
        "YBS4180233 - YÖNETİM BILIŞİM SİSTEMLERİ GELİŞTİRME PROJESİ – I",
        "YBS4211959 - İŞ ZEKASI VE KARAR VERME",
        "YBS4211962 - YÖNETİM BILIŞİM SİSTEMLERİ GELİŞTİRME PROJESİ – II",
        "YBS4220786 - SİBER GÜVENLİK",
      ],
    },
  },
  {
    id: 38,
    universite: "Ankara Yıldırım Beyazıt Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi: "Esenboğa Külliyesi, Dumlupınar Mah. 06760 Çubuk/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 39,
    universite: "Ostim Teknik Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Ostim OSB Mah. 100. Yıl Bulvarı No:55, 06374 Yenimahalle/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "ENG 111 - Akademik İngilizce I",
        "GRS 121 - Girişimciliğin Temelleri",
        "ISG 101 - İş Sağlığı ve Güvenliği",
        "UHG 151 - Üniversite Hayatına Giriş",
        "YBS 131 - Yönetim Bilişim Sistemleri",
        "YBS 111 - Programlamanın Temelleri I",
        "YBS 141 - Matematik I",
        "YBS 103 - Yönetim ve Organizasyon",
        "YBS 105 - Temel Bilgisayar Bilimleri",
        "ENG 112 - Akademik İngilizce II",
        "GRS 122 - Girişimcilik Projesi",
        "IYE 124 - İş Yeri Eğitimi",
        "UHG 152 - Geleceğin İnşası",
        "EKON 100 - Ekonomiye Giriş",
        "YBS 112 - Programlamanın Temelleri II",
        "YBS 142 - Matematik II",
        "YBS 213 - Çağdaş Yönetim Yaklaşımları",
        "YBS 114 - Psikolojiye Giriş",
      ],
      grade_2: [
        "ATA 101 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "TUR 101 - Türk Dili I",
        "IYU 225 - İş Yeri Uygulaması I",
        "GRS 221 - Girişimcilik ve Sosyal Etki I",
        "YBS 243 - Genel Muhasebe",
        "YBS 231 - Veri Yapıları ve Algoritmalar",
        "YBS 241 - İstatistik I",
        "YBS 245 - Tedarik Zinciri Yönetimi ve Lojistik",
        "YBS 251 - Pazarlama İlkeleri ve E-Ticaret",
        "ATA 102 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "TUR 102 - Türk Dili II",
        "IYU 226 - İş Yeri Uygulaması II",
        "GRS 222 - Girişimcilik ve Sosyal Etki II",
        "YBS 216 - İstatistik II",
        "YBS 218 - Veri Tabanı Yönetim Sistemleri",
        "YBS 220 - Sistem Analizi ve Tasarımı",
        "YBS 214 - Bilgi Güvenliği",
        "YBS 202 - Stratejik Yönetim ve İşletme Politikaları",
      ],
      grade_3: [
        "IYU 325 - İş Yeri Uygulaması III",
        "GRS 321 - Girişimcilik ve Sosyal Etki III",
        "YBS 301 - Yöneylem Araştırması",
        "YBS 305 - Nesneye Dayalı Programlama",
        "YBS 309 - Kurumsal Kaynak Planlama",
        "YBS 457 - Web Tabanlı Uygulama Programlama",
        "YBS 391 - Hukuka Giriş",
        "IYD 326 - İş Yeri Deneyimi I",
        "GRS 322 - Girişimcilik ve Sosyal Etki IV",
        "YBS 356 - Araştırma Yöntemleri ve Yayın Etiği",
        "YBS 304 - Proje Yönetimi",
        "YBS 306 - Yazılım Geliştirme Süreçleri",
        "YBS 308 - Veri Analizi",
        "YBS 310 - Finansal Yönetim",
        "YBS 392 - Bilişim Hukuku",
      ],
      grade_4: [
        "IYD 425 - İş Yeri Deneyimi II",
        "GRS 421 - Girişimcilik ve Sosyal Etki V",
        "YBS 415 - Şirket İnşaası ve Tasarımı",
        "YBS 407 - Karar Destek Sistemleri",
        "YBS 405 - Bilgisayar Ağları",
        "YBS 451 - Yazılım Süreç Yönetimi",
        "IYD 426 - İş Yeri Deneyimi III",
        "YBS 400 - Mezuniyet Projesi",
      ],
    },
  },
  {
    id: 40,
    universite: "Türk Hava Kurumu Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi:
      "Türkkuşu Kampüsü, Bahçekapı Mah. Okul Sok. No:11, 06790 Etimesgut/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 41,
    universite: "Ankara Hacı Bayram Veli Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Emniyet Mah. Muammer Bostancı Cad. No:4, 06500 Beşevler/Yenimahalle/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "TÜR-101 - Türk Dili I",
        "ING-101 - İngilizce I",
        "TAR-101 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "IKTI101 - İktisada Giriş 1",
        "ISLE101 - Genel İşletme",
        "EKON105 - Matematik",
        "KAMU101 - Hukukun Temel Kavramları",
        "ENFO101 - Bilişim ve İletişim Teknolojileri",
        "EKON107 - İstatistik",
        "IKTI102 - İktisada Giriş 2",
        "ING-102 - İngilizce II",
        "TAR-102 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "TÜR-102 - Türk Dili II",
        "ISLE102 - Yönetim Ve Organizasyon",
        "ISLE107 - Finansal Muhasebe",
        "YBS102 - Programlamaya Giriş",
        "YBS104 - Yönetim Bilişim Sistemleri",
      ],
      grade_2: [
        "YBS201 - Veri Tabanı Yönetim Sistemleri",
        "YBS203 - Nesne Tabanlı Programlama",
        "ISLE205 - Finansal Yönetim",
        "YBS202 - İnternet Programcılığı",
        "ISLE232 - Pazarlama İlkeleri",
        "YBS204 - Sistem Analizi ve Tasarımı",
        "Seçmeli Ders I",
        "Seçmeli Ders II",
        "Seçmeli Ders III",
        "Seçmeli Ders IV",
        "Alan Dışı Seçmeli I",
      ],
      grade_3: [
        "YBS301 - Veri Bilimi ve Analizi",
        "YBS303 - Yazılım Mimarileri",
        "YBS305 - İş Süreç Yönetimi",
        "YBS302 - Yapay Zeka",
        "YBS304 - Kurumsal Bilgi Sistemleri",
        "YBS306 - Bilgi Sistemleri Uygulama Geliştirme",
        "Seçmeli Ders V",
        "Seçmeli Ders VI",
        "Seçmeli Ders VII",
        "Seçmeli Ders VIII",
        "Alan Dışı Seçmeli II",
      ],
      grade_4: [
        "YBS401 - Karar Destek Sistemleri",
        "YBS403 - İş Zekası ve Veri Madenciliği",
        "YBS405 - Dijital İş ve Ticaret",
        "YBS402 - Proje Yönetimi",
        "YBS404 - Bilgisayar Ağları ve Güvenliği",
        "YBS406 - Yenilikçilik Ve Girişimcilik",
        "Seçmeli Ders IX",
        "Seçmeli Ders X",
        "Seçmeli Ders XI",
        "Seçmeli Ders XII",
      ],
    },
  },
  {
    id: 42,
    universite: "Ankara Bilim Üniversitesi",
    fakulte: "İnsan ve Toplum Bilimleri Fakültesi",
    fakulte_adresi:
      "Merkez Kampüs, Çamlıca Mah. Anadolu Bulvarı No:16A, 06200 Yenimahalle/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YBS 111 - İşletmeye ve E- İşletmeye Giriş",
        "YBS 121 - İşletme Matematiği I",
        "YBS 131 - Bilişim Teknolojisine Giriş",
        "YBS 141 - Java ile Programlama ve Algoritmaya Giriş",
        "YBS 161 - Teknoloji Yönetimi ve İnovasyon",
        "TUR 101 - Türk Dili I",
        "HIS 101 - Atatürk İlkeleri ve İnkılapları I",
        "ENG 101 - Akademik İngilizce I",
        "YBS 112 - İnsan Kaynakları Yönetimi",
        "YBS 122 - İşletme Matematiği II",
        "YBS 132 - Ekonomi",
        "YBS 142 - Java - Nesne Tabanlı Programlama",
        "SURD 106 - Sürdürülebilirliğe Giriş",
        "TUR 102 - Türkçe II",
        "HIS 102 - Atatürk İlkeleri ve İnkılapları II",
        "ENG 102 - Akademik İngilizce II",
      ],
      grade_2: [
        "YBS 211 - Üretim ve Faaliyet Yönetimi",
        "YBS 221 - Olasılık ve İstatistik I",
        "YBS 231 - Pazarlama",
        "YBS 241 - Web Tasarımı ve Geliştirmesi",
        "ENG 201 - İletişim Teknikleri I",
        "SEC 01 - Seçmeli Ders 1",
        "SEC 201 - Bölüm Dışı Seçmeli Ders I",
        "YBS 212 - Finans",
        "YBS 222 - Olasılık ve İstatistik II",
        "YBS 232 - Ağ Güvenliği",
        "YBS 242 - YBS için Veritabanı Yönetimi",
        "ENG 202 - İletişim Teknikleri II",
        "SEC 02 - Seçmeli Ders 2",
        "SEC 202 - Bölüm Dışı Seçmeli Ders II",
      ],
      grade_3: [
        "YBS 311 - Optimizasyon ve Karar Verme",
        "YBS 321 - Veri Bilimine Giriş",
        "YBS 331 - Proje Yönetimi",
        "ENG 301 - Akademik ve Mesleki Yazma Becerileri I",
        "SEC 03 - Seçmeli Ders 3",
        "SEC 04 - Seçmeli Ders 4",
        "SEC 301 - Bölüm Dışı Seçmeli Ders III",
        "YBS 312 - Bilgi Sistemleri Analizi ve Tasarımı",
        "YBS 322 - Karar Destek Sistemleri",
        "YBS 351 - Simülasyon ve Modelleme",
        "ENG 302 - Akademik ve Mesleki Yazma Becerileri II",
        "SEC 05 - Seçmeli Ders 5",
        "SEC 06 - Seçmeli Ders 6",
        "SEC 302 - Bölüm Dışı Seçmeli Ders IV",
      ],
      grade_4: [
        "YBS 411 - Stratejik Yönetim",
        "YBS 421 - Bilgi Teknolojileri Hukuku ve Etiği",
        "SEC 07 - Seçmeli Ders 7",
        "SEC 08 - Seçmeli Ders 8",
        "SEC 09 - Seçmeli Ders 9",
        "SEC 401 - Bölüm Dışı Seçmeli Ders V",
        "YBS 412 - Staj",
        "YBS 422 - Proje",
      ],
    },
  },
  {
    id: 43,
    universite: "Ufuk Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "İncek Şehit Savcı Mehmet Selim Kiraz Bulvarı No:129, 06836 Gölbaşı/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 44,
    universite: "Ankara Sosyal Bilimler Üniversitesi",
    fakulte: "Siyasal Bilgiler Fakültesi",
    fakulte_adresi: "Hükümet Meydanı No:2, 06050 Ulus/Altındağ/Ankara",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "MIS101 - Economics-I",
        "MIS103 - Management and Organization",
        "MIS105 - Introduction to Information Systems and Technologies",
        "MIS107 - Introduction to Algorithms and Programming",
        "MIS109 - Calculus",
        "YDL101 - Foreign Language I",
        "AİİT101 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "TURK101 - Türk Dili I",
        "MIS102 - Economics-II",
        "MIS104 - Principles of Marketing",
        "MIS106 - Object Oriented Programming",
        "MIS108 - Introduction to Database",
        "MIS110 - Matrix Theory",
        "YDL102 - Foreign Language II",
        "AİİT102 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "TURK102 - Türk Dili II",
      ],
      grade_2: [
        "MIS201 - Financial Accounting",
        "MIS203 - Statistics",
        "MIS205 - Information Technology Infrastructures",
        "MIS207 - Web Based Application Programming",
        "MIS209 - Strategic Management (Elective-I)",
        "MIS211 - Purchasing Management (Elective-II)",
        "MIS202 - Managerial Accounting",
        "MIS204 - Research Methodology",
        "MIS206 - Managerial Communications",
        "MIS208 - Business Data Communications",
        "MIS210 - Human Factors in Computing (Elective-III)",
        "MIS212 - Integrated Marketing Communications (Elective-IV)",
      ],
      grade_3: [
        "MIS301 - System Analysis and Design",
        "MIS303 - Data Mining",
        "MIS305 - Database Systems",
        "MIS307 - Cyber Law",
        "MIS311 - Entrepreneurship in IT (Elective-V)",
        "MIS313 - Leadership and Motivation (Elective-VI)",
        "MIS302 - Finance",
        "MIS304 - Object Oriented Modeling",
        "MIS306 - Business Application Development",
        "MIS308 - Quantitative Analysis for Decision Making",
        "MIS310 - Enterprise Information Systems",
        "MIS314 - Systems Dynamic Modeling (Elective-VII)",
      ],
      grade_4: [
        "MIS401 - Information System Project Management",
        "MIS403 - Customer Relationship Management",
        "MIS405 - Decision Support Systems for Business",
        "MIS407 - Senior Seminars in MIS",
        "MIS409 - Internship-I",
        "MIS402 - Cyber Security",
        "MIS404 - Knowledge Management",
        "MIS406 - Special Topics in MIS",
        "MIS408 - Ethical Issues in Computing",
        "MIS410 - Internship-II",
      ],
    },
  },
];
