import { temelYBSDersleri } from "./temelybs";

export const doguYbs = [
  {
    id: 79,
    universite: "Atatürk Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Atatürk Üniversitesi Kampüsü, 25240 Yakutiye/Erzurum",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 80,
    universite: "Fırat Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Fırat Üniversitesi Kampüsü, 23119 Merkez/Elazığ",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "İKT 101 - Microeconomics / Mikro İktisat",
        "TRD 109 - Turkish I / Türkçe I",
        "YBS 103 - Business Management / İşletme Yönetimi",
        "YBS 105 - Introduction to Information Systems and Technologies / Bilişim Sistemleri ve Teknolojilerine Giriş",
        "YBS 107 - Introduction to Algorithms and Programming / Algoritma ve Programlamaya Giriş",
        "YBS 109 - Business Mathematics I / İşletme Matematiği I",
        "YBS 111 - Accounting I / Muhasebe I",
        "YDİ 107 - English I / İngilizce I",
        "İKT 102 - Macroeconomics / Makro İktisat",
        "TRD 110 - Turkish II / Türkçe II",
        "YBS 104 - Management and Organization / Yönetim ve Organizasyon",
        "YBS 106 - Object Oriented Programming I / Nesne Tabanlı Programlama I",
        "YBS 108 - Introduction to Database / Veri Tabanına Giriş",
        "YBS 110 - Business Mathematics II / İşletme Matematiği II",
        "YBS 112 - Accounting II / Muhasebe II",
        "YDİ 108 - English II / İngilizce II",
      ],
      grade_2: [
        "AİT 209 - Principles of Atatürk and History of Turkish Revolution I / Atatürk İlkeleri ve İnkılap Tarihi I",
        "YBS 201 - Financial Management I / Finansal Yönetim I",
        "YBS 203 - Statistics / İstatistik",
        "YBS 205 - Web Based Application Development / Web Tabanlı Uygulama Geliştirme",
        "YBS 207 - Computer Hardware and System Software / Bilgisayar Donanımı ve Sistem Yazılımı",
        "YBS 209 - Marketing Principles / Pazarlama İlkeleri",
        "YBS 211 - Object Oriented Programming II / Nesne Tabanlı Programlama II",
        "AİT 210 - Principles of Atatürk and History of Turkish Revolution II / Atatürk İlkeleri ve İnkılap Tarihi II",
        "YBS 202 - Financial Management II / Finansal Yönetim II",
        "YBS 204 - Research Methods / Araştırma Yöntemleri",
        "YBS 206 - Managerial Communication / Yönetimsel İletişim",
        "YBS 208 - Data Communication and Networks / Veri İletişimi ve Ağlar",
        "YBS 210 - IT English / Bilişim İngilizcesi",
        "YBS 212 - Production Management / Üretim Yönetimi",
      ],
      grade_3: [
        "YBS 301 - Systems Analysis and Design / Sistem Analizi ve Tasarımı",
        "YBS 303 - Data Mining / Veri Madenciliği",
        "YBS 305 - Database Systems / Veritabanı Sistemleri",
        "YBS 307 - IT Law / Bilişim Hukuku",
        "YBS 309 - Operations Research / Yöneylem Araştırması",
        "YBS 311 - Project Management / Proje Yönetimi",
        "YBS 313 - Professional Practice I / Mesleki Uygulama-I",
        "YBS 302 - Enterprise Information Systems / Kurumsal Bilgi Sistemleri",
        "YBS 304 - Web Design Techniques / Web Tasarımı Teknikleri",
        "YBS 306 - Business Application Development / İş Uygulamaları Geliştirme",
        "YBS 308 - Numerical Analysis in Decision Making / Karar Vermede Sayısal Analiz",
        "YBS 310 - E-Commerce and E-Business / Elektronik Ticaret ve Elektronik İşletme",
        "YBS 312 - Big Data and Business Analytics / Büyük Veri ve İş Analitiği",
      ],
      grade_4: [
        "YBS 403 - Customer Relationship Management / Müşteri İlişkileri Yönetimi",
        "YBS 405 - Decision Support Systems for Businesses / İşletmeler için Karar Destek Sistemleri",
        "YBS 407 - Professional Practice II / Mesleki Uygulama-II",
        "YBS 402 - Supply Chain Management / Tedarik Zinciri Yönetimi",
        "YBS 404 - Graduation Project / Bitirme Projesi",
        "Selected Electives / Seçmeli Dersler (Yapay Zeka, Mobil Uygulama Geliştirme, Dijital Pazarlama vb.)",
      ],
    },
  },
  {
    id: 81,
    universite: "Kafkas Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Paşaçayırı Kampüsü, 36100 Merkez/Kars",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 82,
    universite: "Bingöl Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Selahaddin-i Eyyubi Mah. Aydınlık Cad. No:1, 12000 Merkez/Bingöl",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 83,
    universite: "Malatya Turgut Özal Üniversitesi",
    fakulte: "İşletme ve Yönetim Bilimleri Fakültesi",
    fakulte_adresi:
      "Alacakapı Mah. Kırkgöz Cad. No:70, 44210 Battalgazi/Malatya",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },

  // ================= KKTC & YURT DIŞI =================
  {
    id: 84,
    universite: "Doğu Akdeniz Üniversitesi",
    fakulte: "İşletme ve Ekonomi Fakültesi",
    fakulte_adresi: "Doğu Akdeniz Üniversitesi Kampüsü, 99628 Gazimağusa, KKTC",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 85,
    universite: "Bahçeşehir Kıbrıs Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi: "Alayköy, Lefkoşa, KKTC",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 86,
    universite: "Hoca Ahmet Yesevi Uluslararası Türk-Kazak Üniversitesi",
    fakulte: "TÜRTEP (Uzaktan Eğitim)",
    fakulte_adresi: "Türkistan Yerleşkesi, Kazakistan (Türkiye Ofisi: Ankara)",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
];
