import { temelYBSDersleri } from "./temelybs";

export const egeYbs = [
  // ================= İZMİR & EGE BÖLGESİ =================
  {
    id: 45,
    universite: "Dokuz Eylül Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Dokuzçeşmeler Kampüsü, Adatepe Mah. Doğuş Cad. No:207, 35160 Buca/İzmir",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "ATA 1001 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "IBF 1001 - HUKUKUN TEMEL KAVRAMLARI",
        "IBF 1005 - MATEMATİK I",
        "IKT 1011 - İKTİSADA GİRİŞ I",
        "ISL 1055 - FİNANSAL MUHASEBE I",
        "KPD 1000 - Kariyer Planlama",
        "TDL 1001 - Türk Dili I",
        "YBS 1001 - YÖNETİM BİLİŞİM SİSTEMLERİ I",
        "YBS 1003 - VERİ YAPISI VE ALGORİTMALAR",
        "YDİ 1009 - Yabancı Dil I (İngilizce)",
        "ATA 1002 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "EMT 1004 - TEMEL BİLGİ TEKNOLOJİLERİ",
        "IBF 1006 - MATEMATİK II",
        "IKT 1002 - İKTİSADA GİRİŞ II",
        "ISL 1004 - FİNANSAL MUHASEBE II",
        "TDL 1002 - Türk Dili II",
        "YBS 1004 - YÖNETİM BILIŞİM SİSTEMLERİ II",
        "YBS 1006 - PROGRAMLAMA I",
        "YDİ 1008 - Yabancı Dil II (İngilizce)",
      ],
      grade_2: [
        "IBF 1007 - İSTATİSTİK I",
        "ISL 1003 - İŞLETME BİLİMİ",
        "YBS 2007 - BİLİŞİMDE TEKNOLOJİK ARAŞTIRMA YÖNTEMLERİ",
        "YBS 2009 - VERİTABANI YÖNETİM SİSTEMLERİ I",
        "YBS 2011 - İŞLEMLER PLANLAMASI VE ÜRETİM BİLGİ SİSTEMİ YÖNETİMİ",
        "YBS 2013 - BİLGİSAYAR DONANIMI",
        "YBS 2015 - PROGRAMLAMA II",
        "IBF 1008 - İSTATİSTİK II",
        "ISL 2014 - PAZARLAMA",
        "YBS 2004 - BİLGİ TEKNOLOJİLERİ PROJE YÖNETİMİ",
        "YBS 2014 - COĞRAFİ BİLGİ SİSTEMLERİ",
        "YBS 2016 - BİLGİSAYAR AĞLARI",
        "YBS 2020 - VERİTABANI YÖNETİM SİSTEMLERİ II",
        "YBS 2022 - WEB TASARIM TEKNİKLERİ",
      ],
      grade_3: [
        "EMT 3011 - YÖNEYLEM ARAŞTIRMASI I",
        "ISL 4046 - BİLİŞİM HUKUKU",
        "YBS 3007 - BİLİŞİM SİSTEMLERİ ANALİZİ VE TASARIMI",
        "YBS 3009 - MEKANSAL VERİTABANLAR",
        "YBS 3015 - KARAR DESTEK SİSTEMLERİ",
        "YBS 3019 - SUNUCU TABANLI PROGRAMLAMA",
        "EMT 3006 - YÖNEYLEM ARAŞTIRMASI II",
        "YBS 3018 - VERİ MADENCİLIĞİ VE BİLGİ ÇIKARIMI",
        "YBS 3020 - COĞRAFİ BİLGİ SİSTEMLERİNDE KURUMSAL UYGULAMALAR",
        "YBS 3022 - E-TİCARET VE E-İŞ",
        "YBS 3026 - UZAKTAN ALGILAMA",
        "YBS 3028 - YÖNETİŞİM VE E-DEVLET",
      ],
      grade_4: [
        "EMT 4009 - BENZETİM TEORİSİ",
        "YBS 4003 - BİLGİ VE İLETİŞİM TEKNOLOJİLERİ YÖNETİMİ",
        "YBS 4007 - BÜYÜK VERİ VE İŞ ANALİTİĞİ",
        "YBS 4017 - BILIŞİM SEKTÖRÜNDE GİRİŞİMCİLİK",
        "YBS 4019 - SOSYAL MEDYA ANALİZİ VE YÖNETİMİ",
        "YBS 4002 - YÖNETİM BILIŞİM SİSTEMLERİ SEMİNERİ",
        "YBS 4004 - SİSTEM GÜVENLİĞİ",
        "YBS 4008 - KURUMSAL KAYNAK PLANLAMASI",
        "YBS 4010 - KURUMSAL BİLGİ SİSTEMLERİ",
        "YBS 4022 - MOBİL UYGULAMA GELİŞTİRME",
      ],
    },
  },
  {
    id: 46,
    universite: "İzmir Bakırçay Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Gazi Mustafa Kemal Mah. Kaynaklar Cad. Seyrek Yerleşkesi, 35665 Menemen/İzmir",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "MIS 101 - Introduction to Algorithms and Programming / Algoritmalar ve Programlamaya Giriş",
        "MIS 103 - Introduction to Information Systems / Bilişim Sistemlerine Giriş",
        "IKT 193 - Introduction to Economics / İktisata Giriş",
        "ISL 195 - Introduction to Business / İşletmeciliğe Giriş",
        "FS 111 - Calculus I / Matematik I",
        "ATA 101 - Principles of Atatürk and History of Turkish Revolution I",
        "TDL 101 - Turkish I / Türk Dili I",
        "MIS 102 - Computer Programming / Bilgisayar Programlama",
        "ISL 191 - Marketing Principles / Pazarlama İlkeleri",
        "ISL 194 - Entrepreneurship and Innovation / Girişimcilik ve İnovasyon",
        "FS 112 - Calculus II / Matematik II",
        "ISL 197 - Introduction to Accounting / Muhasebeye Giriş",
        "ATA 102 - Principles of Atatürk and History of Turkish Revolution II",
        "TDL 102 - Turkish II / Türk Dili II",
      ],
      grade_2: [
        "MIS 231 - Database Management Systems / Veritabanı Yönetim Sistemleri",
        "MIS 210 - Object-Oriented Programming / Nesne-Tabanlı Programlama",
        "FS 215 - Probability and Statistics / Olasılık ve İstatistik",
        "MIS 251 - User Interface Development / Kullanıcı Arayüzü Geliştirme",
        "Alan Dışı Seçmeli I",
        "MIS 232 - Information Systems Analysis and Design / Bilişim Sistemlerinin Analizi ve Tasarımı",
        "MIS 234 - Data Modeling and Visualization / Veri Modelleme ve Görselleştirme",
        "MIS 236 - Operations Research / Yöneylem Araştırması",
        "MIS 221 - Digital Transformation / Dijital Dönüşüm",
        "Alan Dışı Seçmeli II",
      ],
      grade_3: [
        "MIS 351 - Information Systems Project Management / Bilişim Sistemleri Proje Yönetimi",
        "MIS 333 - Operations and Supply Chain Management / İşlemler ve Tedarik Zinciri Yönetimi",
        "MIS 335 - Predictive Analytics / Tahminsel Analitik",
        "Seçmeli Ders I",
        "Seçmeli Ders II",
        "MIS 332 - Enterprise Information Systems / Kurumsal Bilişim Sistemleri",
        "MIS 334 - Digital Business Management / Dijital İşletme Yönetimi",
        "MIS 336 - Artificial Intelligence Fundamentals / Yapay Zekanın Temelleri",
        "Seçmeli Ders III",
        "Seçmeli Ders IV",
      ],
      grade_4: [
        "MIS 411 - Graduation Project I / Bitirme Projesi I",
        "Seçmeli Ders V",
        "Seçmeli Ders VI",
        "Seçmeli Ders VII (8. Yarıyıl)",
        "Seçmeli Ders VIII (8. Yarıyıl)",
        "Seçmeli Ders IX (8. Yarıyıl)",
        "Seçmeli Ders X (8. Yarıyıl)",
        "Seçmeli Ders XI (8. Yarıyıl)",
      ],
    },
  },
  {
    id: 47,
    universite: "İzmir Demokrasi Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Üçkuyular Mah. Gürsel Aksel Bulvarı No:14, 35140 Karabağlar/İzmir",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 48,
    universite: "Pamukkale Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Kınıklı Kampüsü, Çamlaraltı Mah. Üniversite Cad. No:11, 20070 Pamukkale/Denizli",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YBS101 - YÖNETİM BİLİŞİM SİSTEMLERİNE GİRİŞ",
        "YBS103 - PROGRAMLAMAYA GİRİŞ",
        "ISLE101 - İŞLETMEYE GİRİŞ",
        "GENEL EKONOMİ",
        "EKNM103 - MATEMATİK-I",
        "YABANCI DİL-I",
        "AIT101 - ATATÜRK İLKELERİ VE İNKILAP TARİHİ-I",
        "YBS102 - NESNEYE YÖNELİK PROGRAMLAMA",
        "YBS104 - İŞLETME YÖNETİMİ",
        "ISLE122 - GENEL MUHASEBE",
        "ISLE318 - PAZARLAMA",
        "EKNM104 - MATEMATİK-II",
        "YABANCI DİL-II",
        "AIT102 - ATATÜRK İLKELERİ VE İNKILÂP TARİHİ-II",
      ],
      grade_2: [
        "YBS201 - VERİ YAPILARI VE ALGORİTMALAR",
        "YBS203 - İLERİ OFİS PROGRAMLARI",
        "YBS205 - HUKUKA GİRİŞ",
        "ISLE315 - ÖRGÜTSEL DAVRANIŞ",
        "EKNM201 - İSTATİSTİK-I",
        "TKD201 - TÜRK DİLİ-I",
        "Seçmeli-1 (Güz)",
        "YBS202 - VERİTABANI YÖNETİMİ VE MODELLEMESİ",
        "YBS204 - ARAŞTIRMA YÖNTEMLERİ",
        "ISLE308 - İNSAN KAYNAKLARI YÖNETİMİ",
        "ISLE226 - FİNANSAL YÖNETİME GİRİŞ",
        "EKNM202 - İSTATİSTİK-II",
        "TKD202 - TÜRK DİLİ-II",
        "YBS280 - STAJ-I",
        "Seçmeli-2 (Bahar)",
      ],
      grade_3: [
        "YBS301 - İNTERNETTE PAZARLAMA-I",
        "YBS303 - WEB TABANLI TEKNOLOJİLER",
        "YBS305 - SİSTEM ANALİZİ VE TASARIM",
        "Seçmeli-3 (Güz)",
        "Seçmeli-4 (Güz)",
        "YBS302 - İNTERNETTE PAZARLAMA-II",
        "YBS304 - YAZILIM MÜHENDİSLİĞİ",
        "YBS306 - BİLİŞİM HUKUKU",
        "YBS380 - STAJ-II",
        "Seçmeli-5 (Bahar)",
        "Seçmeli-6 (Bahar)",
      ],
      grade_4: [
        "YBS401 - E-İŞLETMECİLİK",
        "YBS403 - OPTİMİZASYON TEKNİKLERİ",
        "YBS491 - LİSANS TEZİ-I",
        "Seçmeli-3 (Güz)",
        "Seçmeli-4 (Güz)",
        "YBS402 - KARAR DESTEK SİSTEMLERİ",
        "ISLE410 - STRATEJİK YÖNETİM",
        "YBS492 - LİSANS TEZİ-II",
        "Seçmeli-5 (Bahar)",
        "Seçmeli-6 (Bahar)",
      ],
    },
  },
  {
    id: 49,
    universite: "Muğla Sıtkı Koçman Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Kötekli Kampüsü, 48000 Menteşe/Muğla",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 50,
    universite: "Aydın Adnan Menderes Üniversitesi",
    fakulte: "Söke İşletme Fakültesi",
    fakulte_adresi: "Yenicami Mah. Yüksel Yalova Cad. No:57, 09200 Söke/Aydın",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 51,
    universite: "Afyon Kocatepe Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Ahmet Necdet Sezer Kampüsü, Gazlıgöl Yolu, 03200 Merkez/Afyonkarahisar",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 52,
    universite: "Kütahya Dumlupınar Üniversitesi",
    fakulte: "Kütahya Uygulamalı Bilimler Fakültesi",
    fakulte_adresi:
      "Evliya Çelebi Yerleşkesi, Tavşanlı Yolu 10.km, 43100 Merkez/Kütahya",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
];
