import { temelYBSDersleri } from "./temelybs";

export const icAnadoluYbs = [
  // ================= İÇ ANADOLU (DİĞER) =================
  {
    id: 67,
    universite: "Anadolu Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi", // Açıköğretim değil, örgün eğitim için İİBF
    fakulte_adresi:
      "Yunus Emre Kampüsü, Yeşiltepe Mah. 26470 Tepebaşı/Eskişehir",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "İKT101U - İktisada Giriş",
        "İŞL105U - İşletme İlkeleri",
        "MAT105U - Matematik I",
        "MUH101U - Genel Muhasebe",
        "YBS101U - Bilişim Teknolojileri",
        "Yabancı Dil I (İngilizce/Almanca/Fransızca)",
        "HUK124U - Bilişim Hukuku",
        "İKT102U - Proje Yönetimi",
        "İLT102U - Yeni İletişim Teknolojileri",
        "İŞL106U - İşletme Fonksiyonları",
        "MAT106U - Matematik II",
        "Yabancı Dil II (İngilizce/Almanca/Fransızca)",
      ],
      grade_2: [
        "İST203U - İstatistik",
        "TAR201U - Atatürk İlkeleri ve İnkılap Tarihi I",
        "TÜR201U - Türk Dili I",
        "YBS201U - Bilgisayar ve Programlamaya Giriş",
        "YBS203U - İşlem Tabloları",
        "YBS207U - Bilişim Sistemleri",
        "TAR202U - Atatürk İlkeleri ve İnkılap Tarihi II",
        "TÜR202U - Türk Dili II",
        "YBS202U - İşletme Analitiği",
        "YBS204U - Algoritmalar ve Programlama",
        "YBS206U - Veritabanı Sistemleri",
        "YBS208U - İş Süreçleri Yönetimi",
      ],
      grade_3: [
        "BİL109U - Dijital Dönüşüm",
        "İŞL303U - Üretim Yönetimi",
        "YBS301U - İşlem Tablosu Programlama",
        "YBS303U - Kullanıcı Deneyimi Tasarımı",
        "YBS305U - Sistem Analizi ve Tasarımı",
        "YBS307U - Kurumsal Kaynak Planlama Sistemleri",
        "MAİ102U - Marka ve Yönetimi",
        "SOS110U - Örgütsel Davranış",
        "YBS302U - Ağ Yönetimi ve Bilgi Güvenliği",
        "YBS304U - Veritabanı Programlama",
        "YBS306U - İleri Programlama",
        "YBS308U - Sosyal Ağ Analizi",
      ],
      grade_4: [
        "İŞL293U - Girişimcilik ve İş Kurma",
        "İŞY203U - Yenilik Yönetimi",
        "YBS401U - Yöneylem Araştırması",
        "YBS403U - Karar Modelleri",
        "YBS405U - İnternet ve Web Programlama",
        "FİN402U - Finansal Tablolar Analizi",
        "PZL208U - Müşteri İlişkileri Yönetimi",
        "YBS402U - Karar Destek Sistemleri",
        "YBS404U - Veri Madenciliği",
        "YBS406U - Programlamada Yeni Eğilimler",
      ],
    },
  },
  {
    id: 68,
    universite: "Selçuk Üniversitesi",
    fakulte: "Beyşehir Ali Akkanat İşletme Fakültesi",
    fakulte_adresi: "Dalyan Mah. 41604. Sok. No:2, 42700 Beyşehir/Konya",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "3004101 - TEMEL BİLGİ TEKNOLOJİLERİ",
        "3004102 - İŞLETME BİLİMİNE GİRİŞ I",
        "3004103 - GENEL MUHASEBE",
        "3004105 - İŞLETME MATEMATİĞİ",
        "3004106 - ATATÜRK İLKELERİ VE İNKILAP TARİHİ 1",
        "3004107 - TÜRK DİLİ I",
        "3004152 - İKTİSADA GİRİŞ I",
        "3004201 - VERİ YAPILARI VE ALGORİTMA",
        "3004202 - YÖNETİM BİLİŞİM SİSTEMLERİ",
        "3004203 - İŞLETME BİLİMİNE GİRİŞ II",
        "3004206 - ATATÜRK İLKELERİ VE İNKILAP TARİHİ 2",
        "3004207 - TÜRK DİLİ II",
        "3004253 - İKTİSADA GİRİŞ II",
      ],
      grade_2: [
        "3004301 - NESNEYE YÖNELİK PROGRAMLAMA",
        "3004302 - VERİ TABANI VE YÖNETİM SİSTEMLERİ",
        "3004303 - YÖNETİM VE ORGANİZASYON I",
        "3004304 - İSTATİSTİK",
        "3004305 - Pazarlama Yönetimi",
        "3004306 - YABANCI DİL",
        "3004401 - GÖRSEL PROGRAMLAMA",
        "3004402 - SİSTEM ANALİZİ VE TASARIMI",
        "3004403 - YÖNETİM ORGANİZASYON II",
        "3004404 - Yöneylem Araştırması",
        "3004405 - YAZIŞMA TEKNİKLERİ",
        "3004406 - Dijital Pazarlama",
      ],
      grade_3: [
        "3004501 - YAPAY ZEKA",
        "3004502 - İNSAN KAYNAKLARI YÖNETİMİ",
        "3004503 - GİRİŞİMCİLİK",
        "3004508 - WEB PROGRAMLAMA (Seçmeli)",
        "3004518 - BİLİŞİM SEKTÖR PAZARLAMASI (Seçmeli)",
        "3004525 - AYRIK MATEMATİK (Seçmeli)",
        "3004601 - İLERİ PROGRAMLAMA",
        "3004602 - VERİ MADENCİLİĞİ",
        "3004612 - WEB PROJE UYGULAMALARI (Seçmeli)",
        "3004618 - E-Müşteri İlişkiler Yönetimi (Seçmeli)",
        "3004621 - BÜTÜNLEŞİK PAZARLAMA İLETİŞİMİ (Seçmeli)",
        "3004622 - Ekonometri (Seçmeli)",
      ],
      grade_4: [
        "3004701 - MODERN YÖNETİM TEKNİKLERİ",
        "3004712 - BİLGİSAYAR AĞLARI VE GÜVENLİĞİ (Seçmeli)",
        "3004715 - ARAŞTIRMA YÖNTEM VE TEKNİKLERİ (Seçmeli)",
        "3004724 - KALİTE YÖNETİMİ (Seçmeli)",
        "3004729 - VERİ ANALİZİ (Seçmeli)",
        "3004801 - STRATEJİK YÖNETİM",
        "3004812 - Oyun Teorisi ve Stratejik Karar Verme (Seçmeli)",
        "3004814 - İNTERNET PROGRAMCILIĞI (Seçmeli)",
        "3004823 - Finansal Okur Yazarlık (Seçmeli)",
        "3004873 - BİLGİ EKONOMİSİ (Seçmeli)",
      ],
    },
  },
  {
    id: 69,
    universite: "Necmettin Erbakan Üniversitesi",
    fakulte: "Uygulamalı Bilimler Fakültesi",
    fakulte_adresi:
      "Köyceğiz Yerleşkesi, Dere Aşıklar Mah. Demeç Sok. No:42, 42090 Meram/Konya",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YBS 101 - Yönetim Bilişim Sistemleri",
        "YBS 103 - Genel Matematik",
        "YBS 105 - Algoritma ve Programlama-I",
        "YBS 107 - Hukuka Giriş",
        "YBS 109 - Bilgi Teknolojileri ve Uygulamaları",
        "TDL101 - Türk Dili I",
        "AİT101 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "AYD101 - Akademik Yazım Dersi",
        "YBS102 - Ekonomi",
        "YBS104 - Genel İşletme",
        "YBS106 - Algoritma ve Programlama-II",
        "YBS108 - İleri Office Uygulamaları",
        "YBS110 - Genel Muhasebe",
        "TDL102 - Türk Dili II",
        "AİT102 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "KRP102 - Kariyer Planlama",
      ],
      grade_2: [
        "YBS201 - Araştırma Yöntemleri",
        "YBS203 - Nesneye Yönelik Programlama",
        "YBS205 - Pazarlama Yönetimi",
        "YBD101 - Yabancı Dil I",
        "BTF201 - Bilim Tarihi ve Felsefesi",
        "Seçmeli Ders III (Etiğin/Örgüt/İKY/Sistem Analizi vb.)",
        "YBS202 - Yönetim Bilimi",
        "YBS204 - Görsel Programlama",
        "YBS206 - Veritabanı Yönetim Sistemleri",
        "YBD102 - Yabancı Dil II",
        "Seçmeli Ders IV (Bilişim Hukuku/ERP/Sosyal Medya vb.)",
      ],
      grade_3: [
        "YBS301 - Çağdaş Yönetim Teknikleri",
        "YBS303 - Web Tasarımı",
        "YBS305 - Kamu Yönetimi",
        "YBS307 - İstatistik I",
        "Seçmeli Ders V (Yapay Zeka/Veri Madenciliği/Blockchain vb.)",
        "YBS302 - Kurumsal Bilgi Yönetimi",
        "YBS304 - Web Programlama",
        "YBS306 - İstatistik II",
        "YBS308 - Girişimcilik Kültürü",
        "ELD302 - Eleştirel Düşünme",
        "Seçmeli Ders VI (Mobil Programlama/Machine Learning/UX vb.)",
      ],
      grade_4: [
        "YBS401 - Zorunlu İşbaşı Eğitimi I (Full Semester)",
        "YBS402 - Zorunlu İşbaşı Eğitimi II (Full Semester)",
        "Pedagojik Formasyon Seçmeli Grubu (Öğretmenlik Hedefleyenler İçin)",
      ],
    },
  },
  {
    id: 70,
    universite: "Konya Gıda ve Tarım Üniversitesi",
    fakulte: "Sosyal ve Beşeri Bilimler Fakültesi",
    fakulte_adresi: "Melikşah Mah. Beyşehir Cad. No:9, 42080 Meram/Konya",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "UNIV 1001 - English I / İngilizce I",
        "CENG 1003 - Introduction to Computer Applications / Bilgisayar Uygulamalarına Giriş",
        "UNIV 1005 - Calculus I / Matematik I",
        "ITBD 1001 - Introduction to Management / Yönetime Giriş",
        "ECOD 1011 - Introduction to Microeconomics / Mikroiktisada Giriş",
        "UNIV 1011 - Social Responsibility / Sosyal Sorumluluk",
        "UNIV 1017 - Occupational Health and Safety / İş Sağlığı ve Güvenliği",
        "UNIV 1015 - Turkish Language and Literature I / Türk Dili ve Edebiyatı I",
        "UNIV 1002 - English II / İngilizce II",
        "CENG 1004 - Introduction to Programming (Python) / Programlamaya Giriş (Python)",
        "UNIV 1006 - Calculus II / Matematik II",
        "MIS 1004 - Information Management / Bilgi Yönetimi",
        "ECOD 1002 - Introduction to Macroeconomics / Makroiktisada Giriş",
        "MIS 1002 - Introduction to Management Information Systems / Yönetim Bilişim Sistemlerine Giriş",
        "UNIV 1016 - Turkish Language and Literature II / Türk Dili ve Edebiyatı II",
        "UNIV 1024 - Career Planning / Kariyer Planlama",
      ],
      grade_2: [
        "UNIV 2029 - Statistics I / İstatistik I",
        "MIS 2001 - Scientific Programming / Bilimsel Programlama",
        "ITBD 2011 - Fundamentals of Accounting / Muhasebenin Temelleri",
        "MIS 2003 - Operating Systems / İşletim Sistemleri",
        "ECOD 2015 - Introduction to Law / Hukuka Giriş",
        "UNIV 2005 - Scientific Technical Writing and Presentation / Bilimsel Teknik Yazım ve Sunum",
        "UNIV 2007 - Principles of Atatürk and History of Turkish Revolution I / Atatürk İlkeleri ve İnkılap Tarihi I",
        "UNIV 2039 - Orientation – Social Sciences and Humanities / Oryantasyon – Sosyal ve Beşeri Bilimler",
        "UNIV 2010 - Statistics II / İstatistik II",
        "MIS 2004 - Algorithms and Programming / Algoritmalar ve Programlama",
        "ITBD 2006 - Financial Accounting / Finansal Muhasebe",
        "ITBD 2002 - Operations Management / Üretim Yönetimi",
        "UNIV 2008 - Principles of Atatürk and History of Turkish Revolution II / Atatürk İlkeleri ve İnkılap Tarihi II",
        "MIS 2002 - Practical Training I / Staj I",
      ],
      grade_3: [
        "ITBD 3009 - Marketing / Pazarlama",
        "ITBD 3003 - Supply Chain Management / Tedarik Zinciri Yönetimi",
        "ITBD 3005 - Corporate Finance / Kurumsal Finans",
        "MIS 3005 - Object Oriented Programming / Nesne Yönelimli Programlama",
        "MIS 3010 - Machine Learning / Makine Öğrenmesi",
        "ITBD 3008 - Operations Research / Yöneylem Araştırması",
        "MIS 3002 - Systems Analysis and Design / Sistem Analizi ve Tasarımı",
        "MIS 3006 - Enterprise Systems / Kurumsal Sistemler",
        "MIS 3016 - Databases / Veritabanları",
        "MIS 3004 - Practical Training II / Staj II",
        "MIS 3014 - Computer Networks / Bilgisayar Ağları",
      ],
      grade_4: [
        "MIS 4007 - Graduation Project I / Bitirme Projesi I",
        "MIS 4008 - Graduation Project II / Bitirme Projesi II",
        "Elective Courses / Seçmeli Dersler (Advanced Machine Learning, Cyber Law, Digital Transformation, vb.)",
      ],
    },
  },
  {
    id: 71,
    universite: "Aksaray Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Bahçesaray Mah. Kampüs Yolu, 68100 Merkez/Aksaray",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 72,
    universite: "Sivas Cumhuriyet Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Kampüs Yerleşkesi, Kayseri Cad. 58140 Merkez/Sivas",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 73,
    universite: "Kapadokya Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Mustafapaşa Yerleşkesi, 50420 Ürgüp/Nevşehir",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "BGY101 - Basic Information Technologies / Temel Bilgi Teknolojileri",
        "BGY103 - Systems Analysis and Design / Sistem Analizi ve Tasarımı",
        "BGY107 - Introduction to Information Technology / Bilişim Teknolojilerine Giriş",
        "DNS101 - Counseling and Career Planning / Danışmanlık ve Kariyer Planlama",
        "LIN101 - English - I / İngilizce - I",
        "TDS163 - Turkish Language - Basic Logic - I / Türk Dili - Temel Mantık Bilgisi - I",
        "YBS107 - Business Management / İşletme Yönetimi",
        "YBS109 - Introduction to Economics - I / İktisada Giriş - I",
        "BGY108 - Computer Networks / Bilgisayar Ağları",
        "YBS110 - General Mathematics / Genel Matematik",
        "YBS114 - Introduction to Algorithms and Programming / Algoritma ve Programlamaya Giriş",
        "YBS116 - Introduction to Economics - II / İktisada Giriş - II",
        "YBS118 - Introduction to Artificial Intelligence / Yapay Zekaya Giriş",
        "YBS140 - Professional Ethics / Mesleki Etik",
      ],
      grade_2: [
        "BGY209 - Programming with Python - I / Python ile Programlama - I",
        "YBS201 - General Accounting / Genel Muhasebe",
        "YBS205 - Statistics / İstatistik",
        "YBS211 - Introduction to Database / Veritabanına Giriş",
        "YBS221 - Information and Cyber Security Fundamentals / Bilgi Güvenliği ve Siber Güvenlik Temelleri (Seçmeli)",
        "YBS223 - Object Oriented Programming / Nesne Tabanlı Programlama (Seçmeli)",
        "YBS208 - Financial Management / Finansal Yönetim",
        "YBS262 - Marketing Management / Pazarlama Yönetimi",
        "ZPY100 - Time and Project Management / Zaman ve Proje Yönetimi",
        "BGY206 - Web Programming - I / Web Programlama - I (Seçmeli)",
        "BGY210 - Programming with Python - II / Python ile Programlama - II (Seçmeli)",
        "YBS224 - Data Structures / Veri Yapıları (Seçmeli)",
      ],
      grade_3: [
        "MTH121 - Artificial Intelligence in Insurance / Sigortacılıkta Yapay Zekâ",
        "SBK373 - Governance in the Digital Age / Dijital Çağda Yönetişim",
        "YAZ307 - Web Programming - II / Web Programlama - II",
        "YBS307 - Digital Marketing and Social Media / Dijital Pazarlama ve Sosyal Medya",
        "YBS309 - Operations Research / Yöneylem Araştırması",
        "YBS313 - Technical English - I / Alan İngilizcesi - I",
        "YBS315 - Operating Systems / İşletim Sistemleri",
        "BGY321 - Mobile Programming - I / Mobil Programlama - I (Seçmeli)",
        "YBS329 - Cyber Attack and Defense - I / Siber Saldırı ve Savunma - I (Seçmeli)",
        "YBS302 - Security Architecture Design / Güvenlik Mimarisi Tasarımı",
        "YBS304 - Enterprise Resource Planning / Kurumsal Kaynak Planlaması",
        "YBS310 - Technical English - II / Alan İngilizcesi - II",
        "YBS312 - Process Management and Digital Transformation / Süreç Yönetimi ve Dijital Dönüşüm",
        "BGY322 - Data Mining and Business Intelligence / Veri Madenciliği ve İş Zekası (Seçmeli)",
        "YAZ324 - Internet of Things / Nesnelerin İnterneti (Seçmeli)",
      ],
      grade_4: [
        "TAS161 - History of Turkish Democracy - I / Türk Demokrasi Tarihi - I",
        "YBS401 - Labor and Social Security Law / İş ve Sosyal Güvenlik Hukuku",
        "YBS403 - Decision Support Systems (DSS) / Karar Destek Sistemleri",
        "YBS411 - Technical English - III / Alan İngilizcesi - III",
        "YBS431 - Machine Learning in Data Science / Veri Biliminde Makine Öğrenmesi (Seçmeli)",
        "YBS410 - Strategic Management / Stratejik Yönetim",
        "YBS462 - IT Law and Ethics / Bilişim Hukuku ve Etiği",
        "BGY424 - Cloud Computing Security / Bulut Bilişim Güvenliği (Seçmeli)",
        "BIP402 - Graduation Project / Bitirme Projesi (Seçmeli)",
        "STA402 - Internship / Staj (Seçmeli)",
        "YBS432 - Neuro Management / Neuro Yönetim (Seçmeli)",
      ],
    },
  },
];
