import { temelYBSDersleri } from "./temelybs";

export const istanbulYbs = [
  {
    id: 1,
    universite: "Boğaziçi Üniversitesi",
    fakulte: "Yönetim Bilimleri Fakültesi",
    fakulte_adresi: "Hisar Kampüsü, Rumeli Hisarı Mah., 34470 Sarıyer/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "EC 101 - Mikroekonominin İlkeleri",
        "MIS 113 - Yönetim ve Organizasyon",
        "MIS 125 - Bilişim Sistemleri Ve Teknolojilerine Giriş",
        "MIS 131 - Algoritmalar ve Programlamaya Giriş",
        "MATH 101 - Analiz I",
        "UNRE - Serbest Seçmeli",
        "EC 102 - Makroekonominin İlkeleri",
        "MIS 116 - Pazarlama Prensipleri",
        "MIS 132 - Nesneye Yönelik Programlama",
        "MIS 134 - Veritabanına Giriş",
        "MATH 201 - Matris Kuramı",
        "UNRE - Serbest Seçmeli",
      ],
      grade_2: [
        "MIS 211 - Finans Muhasebesi",
        "MIS 213 - İstatistik",
        "MIS 233 - Web Tabanlı Uygulama Programlama",
        "MIS 251 - Bilgi Teknolojileri Altyapıları",
        "HSSE - Sosyal Bilimler Seçmeli Ders",
        "TK 221 - Türkçe",
        "MIS 212 - Yönetim Muhasebesi",
        "MIS 224 - Araştırma Yöntemleri",
        "MIS 228 - Yönetimsel İletişim",
        "MIS 252 - İşletmelerde Veri İletişimi",
        "HSSE - Sosyal Bilimler Seçmeli Ders",
        "TK 222 - Türkçe",
      ],
      grade_3: [
        "MIS 321 - Sistem Analiz ve Tasarım",
        "MIS 331 - Veri Madenciliği",
        "MIS 335 - Veritabanı Sistemleri",
        "MIS 353 - Siber Hukuk",
        "COME - Tamamlayıcı Seçmeli Ders",
        "HTR 311 - Atatürk İlkeleri ve Devrim Tarihi",
        "MIS 316 - Finans",
        "MIS 326 - Nesne Yönelimli Modelleme",
        "MIS 336 - İşletme Uygulaması Geliştirme",
        "MIS 344 - Karar Vermede Sayısal Analiz",
        "MIS 346 - Kurumsal Bilgi Sistemleri",
        "HTR 312 - Atatürk İlkeleri ve Devrim Tarihi",
      ],
      grade_4: [
        "MIS 433 - Bilişim Sistemleri Proje Yönetimi",
        "MIS 441 - Müşteri İlişkileri Yönetimi",
        "MIS 463 - İşletmelerde Karar Destek Sistemleri",
        "MIS 481 - Bilişim Yönetim Sistemi Seminerleri",
        "DPTE / COME - Bölüm Seçmeli Dersi / Tamamlayıcı Seçmeli Ders",
        "DPTE - Bölüm Seçmeli Dersi",
        "MIS 400 - Staj",
        "MIS 422 - E-İş Yönetimi",
        "MIS 432 - Tedarik Zinciri Yönetimi",
        "MIS 492 - Proje",
        "DPTE - Bölüm Seçmeli Dersi",
        "DPTE - Bölüm Seçmeli Dersi",
      ],
    },
  },
  {
    id: 2,
    universite: "Marmara Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi:
      "Recep Tayyip Erdoğan Külliyesi, Aydınevler Mah. 34854 Maltepe/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri", // Hem Türkçe hem Almanca tek çatı altında
    dersler: {
      grade_1: [
        "ACC1005 - Muhasebeye Giriş",
        "ATA121 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "BUS1002 - İşletmeye Giriş",
        "ECON1011 - Mikroekonomi",
        "MATH1047 - İşletme Matematiği I",
        "MIS1301 - Bilişim Sistemleri ve Teknolojisine Giriş",
        "TRD121 - Türk Dili I",
        "ACC1006 - Finansal Muhasebe",
        "ATA122 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "ECON1012 - Makroekonomi",
        "MATH1046 - İşletme Matematiği II",
        "MGT1014 - İşletme Yönetimi",
        "MIS1042 - Algoritmalar ve Veri Yapılarılarına Giriş",
        "TRD122 - Türk Dili II",
      ],
      grade_2: [
        "FNCE2003 - Finansın Temelleri",
        "MIS2103 - Bilgisayar Donanımı ve Sistem Yazılımı",
        "MIS2111 - Nesne Yönelimli Programlama",
        "MIS2113 - Veritabanına Giriş",
        "MRK2023 - Pazarlama İlkeleri",
        "STAT2011 - İşletme İstatistiği I",
        "BUS3002 - İnovasyon Yönetimi",
        "FNCE2004 - Finansal Yönetim",
        "MIS2026 - Web Tabanlı Uygulama Programlama",
        "MIS2040 - İleri Veritabanı",
        "MIS2042 - İşletme Veri İletişimi",
        "STAT2012 - İşletme İstatistiği II",
      ],
      grade_3: [
        "BUS2004 - Araştırma Yöntemleri",
        "MIS3001 - Yaz Stajı I",
        "MIS3121 - Veri Madenciliği",
        "MIS3301 - Sistem Analizi ve Tasarımı",
        "MIS-CE1 - Tamamlayıcı Seçmeli Ders 1",
        "MIS-DE1 - Bölüm Seçmeli Dersi 1",
        "LAW4021 - Bilişim Hukuku",
        "MIS3024 - Karar Verme İçin Sayısal Analiz",
        "MIS3302 - Bilişim Sistemleri Proje Yönetimi",
        "MIS3322 - Kurumsal Bilgi Sistemleri",
        "MIS-CE2 - Tamamlayıcı Seçmeli Ders 2",
        "MIS-DE2 - Bölüm Seçmeli Dersi 2",
      ],
      grade_4: [
        "MIS4001 - Yaz Stajı II",
        "MIS4011 - Simülasyon Modelleme ve Analiz",
        "MIS4311 - Makine Öğrenmesi Uygulamaları",
        "MIS4313 - İşletmeler İçin Karar Destek Sistemleri",
        "MIS-DE3,4 - Bölüm Seçmeli Dersi 3,4",
        "MIS4020 - Müşteri İlişkileri Yönetimi",
        "MIS4022 - E-İş Yönetimi",
        "MIS4992 - Proje",
        "MIS-DE5,6 - Bölüm Seçmeli Dersi 5,6",
      ],
    },
  },
  {
    id: 3,
    universite: "İstanbul Üniversitesi",
    fakulte: "İktisat Fakültesi",
    fakulte_adresi: "Beyazıt Kampüsü, 34452 Fatih/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YBSB1003 - Algorithmic Thinking and Design",
        "ODAI0001 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "YBSB1007 - Introduction to Business",
        "YBSB1001 - Introduction to Economics I",
        "YBSB1005 - Introduction to Information Technologies",
        "YBSB1009 - Mathematics I",
        "ODTD0001 - Türk Dili I",
        "ODYD0001 - Yabancı Dil (İngilizce) I",
        "ODAI0002 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "YBSB1010 - Business Mathematics",
        "YBSB1008 - Data Structures and Management",
        "YBSB1002 - Introduction to Economics II",
        "YBSB1006 - Management and Digital Communication",
        "YBSB1004 - Structured Programming",
        "ODTD0002 - Türk Dili II",
        "ODYD0002 - Yabancı Dil (İngilizce) II",
      ],
      grade_2: [
        "YBSB2013 - Cybersecurity",
        "YBSB2015 - Development Environments",
        "YBSB2007 - Fundamentals of Law",
        "YBSB2001 - Intermediate Microeconomics",
        "YBSB2011 - Principles of Marketing",
        "YBSB2003 - Statistics I",
        "YBSB2005 - System Analysis and Design",
        "YBSB2010 - Database Design and Management",
        "YBSB2018 - Entrepreneurship",
        "YBSB2002 - Intermediate Macroeconomics",
        "YBSB2006 - Object Oriented Programming",
        "YBSB2004 - Statistics II",
        "YBSB2008 - Web Design",
      ],
      grade_3: [
        "YBSB3005 - Accounting",
        "YBSB3009 - Business Intelligence",
        "YBSB3011 - Customer Relationship Management",
        "YBSB3007 - E-Commerce Design and Applications",
        "YBSB3003 - Programming for Data Science",
        "YBSB3001 - Web Programming",
        "YBSB3004 - Artificial Intelligence and Machine Learning",
        "YBSB3014 - Blockchain Programming",
        "YBSB3006 - Management and Cost Accounting",
        "YBSB3008 - Project Management",
        "YBSB3002 - Statistical Programming",
        "YBSB3010 - Supply Chain Management",
      ],
      grade_4: [
        "YBSB4009 - Advanced Database Programming",
        "YBSB4001 - Best Practices in MIS",
        "YBSB4007 - Deep Learning",
        "YBSB4005 - Graduation Project I",
        "YBSB4015 - Human Resource Management",
        "YBSB4003 - Software Quality and Testing",
        "YBSB4012 - Digital Transformation",
        "YBSB4004 - Enterprise Resource Planning",
        "YBSB4006 - Graduation Project II",
        "YBSB4002 - Human-Computer Interaction",
        "YBSB4016 - Social Media Management and Analytics",
        "YBSB4014 - Web Mining and Text Mining",
      ],
    },
  },
  {
    id: 4,
    universite: "Gebze Teknik Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi: "Cumhuriyet Mah. 2254. Sk. No:2, 41400 Gebze/Kocaeli",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },

  // ================= İSTANBUL (VAKIF) =================
  {
    id: 5,
    universite: "Özyeğin Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi:
      "Çekmeköy Kampüsü, Nişantepe Mah. Orman Sok. No:34-36, 34794 Çekmeköy/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "MIS 100 - Bilişim Teknolojilerine Giriş",
        "MIS 103 - Bilgisayar Programlamaya Giriş",
        "MIS 104 - Nesneye Dayalı Programlama Temelleri",
        "MIS 311 - Yönetim Bilişim Sistemlerine Giriş",
      ],
      grade_2: [
        "MIS 203 - Veritabanı Yönetimi",
        "MIS 206 - İş Süreçleri Analizi",
        "MIS 313 - Kurumsal Veri ve Bilgi: Organizasyon ve Yönetimi",
        "MIS 315 - Veri Analizi ve Karar Modellemesi",
      ],
      grade_3: [
        "MIS 301 - Kurumsal Bilgi Sistemleri",
        "MIS 303 - İnternet Programlama",
        "MIS 305 - İşletmelerde Dijital Dönüşüm",
        "MIS 309 - Sistem Analizi ve Tasarımı",
        "MIS 317 - İşletmeler için Bulut Bilişim",
        "MIS 321 - Veri Madenciliği",
      ],
      grade_4: [
        "MIS 304 - Bilişim Güvenliği",
        "MIS 306 - E-İş'in Temelleri",
        "MIS 314 - Bilgi Teknolojileri Yönetişimi ve Denetimi",
        "MIS 324 - IS Proje Yönetimi",
        "MIS 403 - Bağımsız Araştırma - MIS",
      ],
    },
  },
  {
    id: 6,
    universite: "Yeditepe Üniversitesi",
    fakulte: "Ticari Bilimler Fakültesi",
    fakulte_adresi:
      "26 Ağustos Yerleşimi, İnönü Mah. Kayışdağı Cad. 34755 Ataşehir/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "ACM105 - Enformatik Yönetimi",
        "AFE131 - Akademik İngilizce I",
        "CIS111 - Yazılım Geliştirmenin Temelleri",
        "ECON111 - Mikroekonominin Temelleri",
        "MATH133 - Temel Matematik",
        "ACM262 - Web Tasarımına Giriş",
        "CIS112 - Nesne Yönelimli Veri Yapıları",
        "CIS116 - Nesne Yönelimli Yazılım Geliştirme",
        "ECON122 - Makroekonominin Temelleri",
        "HUM103 - Uygarlık Tarihi",
        "MATH134 - İleri Matematik",
      ],
      grade_2: [
        "ACM213 - Bilgi Analizi ve Sistem Tasarımı",
        "ACM361 - Ağ Oluşturma I",
        "BBA244 - Finansal Muhasebenin Temelleri",
        "CIS114 - Algoritmalar",
        "STAT410 - İstatistik",
        "TKL201 - Türk Dili I",
        "ACM212 - İleri Veri Tabanı Uygulamaları",
        "ACM312 - Yönetim Bilişim Sistemleri",
        "BBA341 - Yönetim Muhasebesi",
        "CIS113 - Programlama Dillerinin Kavramları",
        "STAT411 - İleri İstatistik Uygulamaları",
        "TKL202 - Türk Dili II",
      ],
      grade_3: [
        "ACM365 - İleri Web Tasarımı",
        "HTR301 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "ACM366 - E-İş",
        "ACM432 - Kurumsal Bilgi Sistemleri",
        "HTR302 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "LAW303 - Hukuka Giriş I",
        "Bölüm Seçmeli I",
        "Bölüm Seçmeli II",
        "Bölüm Seçmeli III",
        "Bölüm Seçmeli IV",
        "Serbest Seçmeli I",
        "Serbest Seçmeli II",
      ],
      grade_4: [
        "ACM421 - Proje Yönetimi",
        "MIS394 - Staj",
        "MIS498 - Bitirme Projesi",
        "Bölüm Seçmeli V",
        "Bölüm Seçmeli VI",
        "Bölüm Seçmeli VII",
        "Bölüm Seçmeli VIII",
        "Bölüm Seçmeli IX",
        "Serbest Seçmeli III",
        "Serbest Seçmeli IV",
      ],
    },
  },
  {
    id: 7,
    universite: "Kadir Has Üniversitesi",
    fakulte: "Yönetim Bilimleri Fakültesi",
    fakulte_adresi:
      "Cibali Kampüsü, Cibali Mah. Kadir Has Cad. 34083 Fatih/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "BUS101 - İşletmeye Giriş",
        "ECON101 - Ekonomiye Giriş I",
        "KHAS103 - İnsanlık Tarihi",
        "KHAS105 - Evrensel Değerler ve Etik",
        "TLL101 - Türkçe Eleştirel Okuma ve Yazma I",
        "BUS331 - Pazarlamanın Prensipleri",
        "KHAS110 - Toplumsal Sorumluluk Projesi",
        "MAT122 - Matematik I",
        "MIS106 - Algoritma Tasarımı ve Programlamaya Giriş",
        "TLL102 - Türkçe Eleştirel Okuma ve Yazma II",
        "Alan Seçmeli I",
        "Serbest Seçmeli I",
      ],
      grade_2: [
        "BUS215 - Finansal Muhasebe",
        "HST101 - Modern Türkiye Tarihi I",
        "MAN201 - İstatistik",
        "MAT123 - Matematik II",
        "MIS201 - BT Temelleri",
        "HST102 - Modern Türkiye Tarihi II",
        "MAN202 - Uygulamalı Doğrusal Cebir",
        "MIS210 - Staj I",
        "MIS220 - Veri, Zeka ve Gerçek Hayat",
        "Alan Seçmeli II",
        "Alan Seçmeli III",
        "Serbest Seçmeli II",
      ],
      grade_3: [
        "IT321 - Bulut Hesaplama",
        "MIS311 - Karar Destek Sistemleri",
        "MIS325 - Veri Madenciliği ve İş Zekasına Giriş",
        "IT304 - Bilgi Sistemleri Analiz ve Tasarımı",
        "IT306 - Sunucu Tarafı Programlama",
        "MIS310 - Staj II",
        "MIS326 - Web ve Sosyal Medya Analizi",
        "Alan Seçmeli IV",
        "Alan Seçmeli V",
      ],
      grade_4: [
        "MIS403 - Kurumsal Bilgi Sistemleri",
        "MIS411 - Enformasyon Teknolojileri Proje Yönetimi",
        "MIS400 - Tasarım Projesi",
        "MIS414 - E-Ticaret Sistemleri",
        "MIS418 - Bilgi ve Teknoloji Yönetimi",
        "Alan Seçmeli VI",
        "Serbest Seçmeli III",
        "Serbest Seçmeli IV",
      ],
    },
  },
  {
    id: 8,
    universite: "İstanbul Bilgi Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi:
      "Santralistanbul Kampüsü, Emniyettepe Mah. Kazım Karabekir Cad. No:2/13, 34060 Eyüpsultan/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "BUS 179 - Uygulamalı İşletme ve Toplum I",
        "EC 101 - Ekonomiye Giriş I",
        "BUS/E 179 - Akademik Beceri Odaklı İngilizce I",
        "CMPE 130 - Algoritmalar ve Programlama",
        "MATH 175 - Analiz I",
        "TK 103 - Türk Dili I",
        "MIS 102 - Orta Düzey Programlama",
        "BUS 120 - İşletme ve Ekonomi için Office Uygulamaları",
        "BUS 180 - Uygulamalı İşletme ve Toplum II",
        "EC 102 - Ekonomiye Giriş II",
        "BUS/E 180 - Akademik Beceri Odaklı İngilizce II",
        "MATH 176 - Analiz II",
        "TK 104 - Türk Dili II",
      ],
      grade_2: [
        "MIS 202 - İşletme Bilişim Sistemleri",
        "BUS 211 - Muhasebeye Giriş",
        "BUS 273 - İşletme için İstatistiki Analiz",
        "HTR 111 - Türk Devrim Tarihi I",
        "BUS 274 - İşletme için İleri İstatistik",
        "MATH 235 - Ekonomi ve İşletme için Analiz",
        "HTR 112 - Türk Devrim Tarihi II",
        "GE Bilim, Muhakeme ve Eleştirel Düşünme Seçmeli",
        "GE Sosyal Bilimler Seçmeli",
        "GE Farkındalık ve Sosyal Sorumluluk Seçmeli",
      ],
      grade_3: [
        "MIS 300 - II. Sınıf Yaz Stajı",
        "MIS 302 - Veritabanı Yönetimi",
        "MIS 303 - İşletmeler için Veri Analitiği",
        "MIS 311 - Sistem Analizi ve Tasarımı I",
        "MIS 306 - İşletmeler için Veri İletişimi",
        "MIS 312 - Sistem Analizi ve Tasarımı II",
        "BUS 314 - Yönetim Bilimi",
        "CMPE 372 - Kullanıcı Arayüzü Tasarımı",
        "MIS Seçmeli Listesi I",
        "MIS Seçmeli Listesi II",
        "BUS Seçmeli Listesi",
      ],
      grade_4: [
        "MIS 400 - III. Sınıf Yaz Stajı",
        "MIS 401 - Kurumsal Sistemler",
        "MIS 461 - Bilişim Teknolojisi Yönetimi",
        "MIS 497 - Bilişim Sistemleri Projesi I",
        "MIS 402 - Yönetim Destek Sistemleri ve Kurumsal Zeka",
        "MIS 498 - Bilişim Sistemleri Projesi II",
        "BUS 462 - e-Ticaret",
        "MIS Seçmeli Listesi",
        "BUS Seçmeli Listesi I",
        "BUS Seçmeli Listesi II",
      ],
    },
  },
  {
    id: 9,
    universite: "MEF Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi: "Ayazağa Cad. No:4, 34396 Maslak/Sarıyer/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 10,
    universite: "İstanbul Medipol Üniversitesi",
    fakulte: "İşletme ve Yönetim Bilimleri Fakültesi",
    fakulte_adresi:
      "Kavacık Güney Yerleşkesi, Göztepe Mah. Atatürk Cad. No:40, 34810 Beykoz/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "İNG 111 - İngilizce I",
        "TDL 111 - Türk Dili I",
        "YBS 1124 - Hukukun Temel Kavramları",
        "YBS 1124 - Matematik I",
        "YBS 1152 - Ekonominin Temelleri",
        "YBS 1141 - Muhasebenin Temel İlkeleri",
        "YBS 1124 - Yönetim Bilişim Sistemleri",
        "İNG 121 - İngilizce II",
        "TDL 122 - Türk Dili II",
        "YBS 1224 - İşletme Bilimine Giriş",
        "YBS 1224 - Bilişim Teknolojileri",
        "YBS 1224 - Matematik II",
        "YBS 1212 - Sunum ve Yazım Teknikleri",
        "YBS 1254 - Programlamaya Giriş ve Algoritmalar",
      ],
      grade_2: [
        "ATA 211 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "YBS 2154 - E-Ticaret",
        "YBS 2134 - Programlama Dilleri I",
        "YBS 2134 - İstatistik I",
        "YBS 2134 - Web Tasarımı Temelleri",
        "YBS 2134 - Yönetim ve Organizasyon",
        "YBS 2190 - Mesleki İngilizce I",
        "ATA 221 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "YBS 2224 - Davranış Bilimleri",
        "YBS 2212 - Yöneylem Araştırması",
        "YBS 2234 - İstatistik II",
        "YBS 2234 - Programlama Dilleri II",
        "YBS 2234 - Algoritma ve Veri Yapıları",
        "YBS 2290 - Mesleki İngilizce II",
      ],
      grade_3: [
        "YBS 3157 - Sistem Analizi ve Tasarımı",
        "YBS 3157 - İşletmelerde Nicel Karar Verme Yöntemleri",
        "YBS 3157 - Veri Tabanı ve Veri Tabanı Yönetim Sistemleri",
        "YBS 3234 - İş ve Meslek Ahlakı",
        "YBS 3257 - Görsel Programlama",
        "YBS 3257 - Nesne Tabanlı Programlama",
        "Programa Bağlı Seçmeli Dersler I",
        "Programa Bağlı Seçmeli Dersler II",
      ],
      grade_4: [
        "YBS 4170 - Veri Madenciliği ve İş Zekası",
        "YBS 4213 - Lisans Bitirme Projesi",
        "Programa Bağlı Seçmeli Dersler III",
        "Programa Bağlı Seçmeli Dersler IV",
      ],
    },
  },
  {
    id: 11,
    universite: "İstanbul Ticaret Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi:
      "Sütlüce Yerleşkesi, Örnektepe Mah. İmrahor Cad. No:88/2, 34445 Beyoğlu/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "LNG101 - General English 1 / Genel İngilizce 1",
        "GNL101 - Ataturk’s Principles and History of Revolution 1 / Atatürk İlkeleri ve İnkılap Tarihi 1",
        "GNL105 - Turkish Language 1 / Türk Dili 1",
        "MAN101 - Business Mathematics 1 / İşletme Matematiği 1",
        "MUD101 - Financial Accounting 1 / Finansal Muhasebe 1",
        "IKT105 - Microeconomics / Mikroekonomi",
        "MAN103 - Fundamentals of Business / İşletmenin Temelleri",
        "LNG102 - General English 2 / Genel İngilizce 2",
        "GNL102 - Ataturk’s Principles and History of Revolution 2 / Atatürk İlkeleri ve İnkılap Tarihi 2",
        "GNL106 - Turkish Language 2 / Türk Dili 2",
        "MAN102 - Business Mathematics 2 / İşletme Matematiği 2",
        "MUD102 - Financial Accounting 2 / Finansal Muhasebe 2",
        "IKT102 - Macroeconomics / Makroekonomi",
        "MAN104 - Introduction to Information Systems and Technologies / Bilişim Sistemleri ve Teknolojilerine Giriş",
      ],
      grade_2: [
        "MAN201 - Statistics / İstatistik",
        "BIL233 - Object Oriented Programming / Nesne Yönelimli Programlama",
        "MAN203 - Introduction to Algorithms and Programming / Algoritmalar ve Programlamaya Giriş",
        "MAN205 - Introduction to Database / Veri Tabanına Giriş",
        "GNL203 - Academic Skill, Method and Ethics / Akademik Beceri, Yöntem ve Etik",
        "ISL208 - Marketing Management / Pazarlama Yönetimi",
        "MUD208 - Managerial Accounting / Yönetim Muhasebesi",
        "ISL102 - Management and Organization / Yönetim ve Organizasyon",
        "MAN202 - Information Technology Infrastructures / Bilgi Teknolojileri Altyapıları",
        "MAN204 - Web Based Application Programming / Web Tabanlı Uygulama Programlama",
        "University Elective / Üniversite Seçmeli Ders",
      ],
      grade_3: [
        "MAN301 - Database Systems / Veri Tabanı Sistemleri",
        "MAN303 - Data Mining / Veri Madenciliği",
        "MAN305 - System Analysis and Design / Sistem Analizi ve Tasarımı",
        "MAN307 - MIS Internsip - 1 / MIS Stajı - 1",
        "MAN302 - Quantitative Analysis for Decision Making / Karar Vermede Sayısal Analiz",
        "MAN304 - ERP Systems / ERP Sistemleri",
        "MAN306 - Cloud Computing Fundamentals / Bulut Bilişimin Temelleri",
        "MAN308 - Business Application Development / İşletme Uygulaması Geliştirme",
        "MAN310 - MIS Internsip - 2 / MIS Stajı - 2",
        "Elective / Seçmeli Ders I",
        "Elective / Seçmeli Ders II",
      ],
      grade_4: [
        "MAN401 - Information System Project Management / Bilişim Sistemleri Proje Yönetimi",
        "MAN403 - Business Applications of AI / İşletmelerde Yapay Zeka Uygulamaları",
        "MAN405 - Strategic Management / Stratejik Yönetim",
        "GNL450 - Career Planning / Kariyer Planlama",
        "MAN402 - E-Business Management / E-İş Yönetimi",
        "MAN404 - Entrepreneurship in Information Technology / Bilişim Teknolojisinde Girişimcilik",
        "MAN406 - MIS Graduation Project / Yönetim Bilişim Sistemleri Bitirme Projesi",
        "Elective / Seçmeli Ders III",
        "Elective / Seçmeli Ders IV",
      ],
    },
  },
  {
    id: 12,
    universite: "İstinye Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi:
      "Vadi Kampüs, Ayazağa Mah. Azerbaycan Cad. No:4B, 34396 Sarıyer/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 13,
    universite: "İstanbul Aydın Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Halit Aydın Yerleşkesi, Beşyol Mah. İnönü Cad. No:38, 34295 Küçükçekmece/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "ENG101 - Mesleki İngilizce I",
        "TLL101 - Türk Dili I",
        "UMI101 - Programlama I",
        "UMI103 - Sistem Analizi ve Algoritmalar",
        "UMI105 - Yönetim Bilişim Sistemleri",
        "UMI107 - Genel Ekonomi",
        "UMI109 - Hukukun Temel Kavramları",
        "UMI111 - İşletmeye Giriş",
        "UMI113 - Matematik I",
        "ENG102 - Mesleki İngilizce II",
        "TLL102 - Türk Dili II",
        "UMI102 - Programlama II",
        "UMI104 - Algoritma ve Veri Yapıları",
        "UMI106 - Nesne Yönelimli Programlama",
        "UMI108 - Yazılım Tasarımı",
        "UMI122 - Genel Muhasebe",
        "UMI124 - Matematik II",
        "UMI126 - Yönetim ve Organizasyon",
      ],
      grade_2: [
        "ATA103 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "SRE101 - Sosyal Sorumluluk ve Etik",
        "UMI201 - Bilgi Sistemleri ve Teknolojileri",
        "UMI203 - Bilgisayar Ağ Sistemleri",
        "UMI205 - İstatistik I",
        "UMI207 - Veri Yapıları ve Veritabanı Uygulamaları",
        "UMI209 - İşletim Sistemleri ve Bilgisayar Donanımı",
        "ATA104 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "UMI202 - Web Tasarım ve Programlama",
        "UMI204 - Veri Madenciliği ve İş Zekası",
        "UMI206 - İstatistik II",
        "UMI208 - Kurumsal Kaynak Planlaması",
        "UMI222 - Betik Dili",
        "UMI224 - Bilgisayar Ağ Programlama",
      ],
      grade_3: [
        "UMI303 - Finansal Yönetim",
        "UMI305 - Bulut Sistemleri",
        "YUM303 - Yerinde Uygulama I",
        "UMI306 - Üretim Yönetimi",
        "UMI308 - Pazarlama Yönetimi",
        "YUM304 - Yerinde Uygulama II",
        "Bölüm Seçmeli Dersleri",
        "Fakülte Seçmeli Dersleri",
      ],
      grade_4: [
        "UMI401 - Bitirme Projesi",
        "UMI421 - Proje Yönetimi",
        "YUM403 - Yerinde Uygulama III",
        "GRI403 - Girişimcilik",
        "UMI402 - Bilgi Sistemleri Güvenliği",
        "UMI404 - Müşteri İlişkileri Yönetimi",
        "UMI406 - Sürdürülebilirlik",
        "Üniversite Seçmeli Dersleri",
      ],
    },
  },
  {
    id: 14,
    universite: "Haliç Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi:
      "5. Levent Kampüsü, Güzeltepe Mah. 15 Temmuz Şehitler Cad. No:14/12, 34060 Eyüpsultan/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "BUS1001 - Introduction to Business",
        "BUS1005 - Mathematics for Business I",
        "BUS1007 - Introduction to Law",
        "CCC0103 - History of Turkish Revolution and Ataturk's Principles I",
        "CCC0105 - Advanced English I",
        "MIS1001 - Computer Hardware",
        "MIS1003 - Introduction to Information Technology",
        "BUS1006 - Mathematics for Business II",
        "BUS1008 - Fundamentals of Economics",
        "CCC0104 - History of Turkish Revolution and Ataturk's Principles II",
        "CCC0106 - Advanced English II",
        "CCC0130 - Career Planning",
        "HLU0020 - Professional Ethics",
        "MIS1002 - Introduction to Programming",
        "UEC11X2 - University Elective-2",
      ],
      grade_2: [
        "BUS2001 - Business Management",
        "HLU2001 - Statistics I",
        "MIS2001 - Web Design",
        "MIS2003 - Software Development",
        "MIS2005 - Principles of Accounting",
        "OZD0101 - Türk Dili I",
        "HLU2002 - Statistics II",
        "MIS2002 - Introduction to Database",
        "MIS2004 - Visual Programming",
        "MIS2006 - Web Programming",
        "NAE2XX2 - Non-Area Elective-4",
        "OZD0102 - Türk Dili II",
      ],
      grade_3: [
        "BUS3001 - Fundamentals of Finance",
        "HLU0120 - Occupational Health and Safety",
        "MIS3001 - Algorithm and Data Structures",
        "MIS3003 - Database Management Systems",
        "MIS3005 - Digital Communication",
        "MIS3007 - Principles of Marketing",
        "BUS3006 - Entrepreneurship and Small Business Management",
        "HLU0010 - Scientific Research Methods",
        "MIS3002 - IT Project Management",
        "MIS3004 - Fundamentals of Artificial Intelligence",
        "ARE3XX2 - Area Elective-6",
        "NAE3XX2 - Non-Area Elective-4",
      ],
      grade_4: [
        "BUS0000 - Internship",
        "BUS4000 - Graduation Project",
        "ARE4XX1 - Area Elective (4 Courses)",
        "ARE4XX2 - Area Elective (4 Courses)",
        "MIS4101 - Digital Product Management (Örnek Seçmeli)",
        "MIS4105 - Computer Networks and Security (Örnek Seçmeli)",
        "MIS4115 - Data Mining (Örnek Seçmeli)",
        "MIS4117 - Business Intelligence and Analytics (Örnek Seçmeli)",
        "MIS4121 - Machine Learning (Örnek Seçmeli)",
        "MIS4108 - Mobile Applications (Örnek Seçmeli)",
      ],
    },
  },
  {
    id: 15,
    universite: "Işık Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi:
      "Şile Kampüsü, Meşrutiyet Mah. Üniversite Sok. No:2, 34980 Şile/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "CORE 0103 - Türkçe I",
        "CORE 0101 - Türkiye Cumhuriyeti Tarihi I",
        "ORDE 0201 - Doğa, Bilim, İnsan I",
        "ENGL1201 - Genel İngilizce I",
        "ORDE 0105 - Oryantasyon",
        "ORDE 0301 - Sayılar, Formüller, İnsan I",
        "ORDE 0501 - Sanat, Toplum, İnsan",
        "YÖBİ1113 - Algoritmalara Giriş",
        "BİTE1001 - Bilgisayar Okuryazarlığı",
        "CORE 0104 - Türkçe II",
        "CORE 0102 - Türkiye Cumhuriyeti Tarihi II",
        "ORDE 0202 - Doğa, Bilim, İnsan II",
        "ENGL1202 - Genel İngilizce II",
        "ORDE 0106 - Kariyer Planlama",
        "MATE1301 - Matematik I",
        "ORDE 0401 - Toplum, Bilim ve İnsan",
        "YÖBİ1114 - Programlamaya Giriş",
      ],
      grade_2: [
        "ORDE 0107 - Yaratıcı Düşünme ve Problem Çözme",
        "ORDE 0402 - Etik, Hukuk ve Toplum",
        "ORDE 0108 - Büyük Eserler",
        "İŞLE1302 - Yönetim İlkeleri",
        "YÖBİ1121 - Bilişim Sistemlerinin Temelleri",
        "ENGL2203 - Genel İngilizce 3A",
        "MATE2201 - Olasılık",
        "MATE2103 - Ayrık Matematik",
        "İŞLE3441 - Pazarlama İlkeleri",
        "ENGL2204 - Genel İngilizce 4A",
        "YÖBİ1106 - Veritabanı Sistemleri ve Uygulamaları",
        "YÖBİ2291 - Endüstri Stajı I",
        "YÖBİ2244 - Bilişim Sistemleri Analizi ve Tasarımı",
      ],
      grade_3: [
        "YÖBİ1101 - Bilişim Yönetimi için Java",
        "YÖBİ2213 - Web Tasarımı ve Programlama",
        "MATE2203 - İstatistik I",
        "BİTE4433 - Veri Ambarlama ve Veri Madenciliği",
        "İŞLE2111 - Finansal Muhasebe",
        "YÖBİ1102 - Bilişim Yönetimi için İleri Java",
        "YÖBİ-GS-I - Genel Seçmeli-I",
        "YÖBİ3116 - İleri Veritabanı Sistemleri",
        "İŞLE2114 - Yönetim Muhasebesi",
        "YÖBİ3391 - Endüstri Stajı II",
        "EKON1005 - İktisada Giriş",
      ],
      grade_4: [
        "YÖBİ4901 - Proje",
        "YÖBİ-GS-II - Genel Seçmeli-II",
        "YÖBİ-AS-I - Alan Seçmeli-I",
        "YÖBİ-GS-III - Genel Seçmeli-III",
        "YÖBİ-AS-II - Alan Seçmeli-II",
        "YÖBİ4461 - Nesnelerin İnterneti",
        "YÖBİ-AS-III - Alan Seçmeli-III",
        "YÖBİ-GS-IV - Genel Seçmeli-IV",
        "YÖBİ-AS-IV - Alan Seçmeli-IV",
        "YÖBİ-GS-V - Genel Seçmeli-V",
        "YÖBİ-AS-V - Alan Seçmeli-V",
      ],
    },
  },
  {
    id: 16,
    universite: "Piri Reis Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Tuzla Sahil Kampüsü, Postane Mah. Eflatun Sk. No:8, 34940 Tuzla/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 17,
    universite: "İstanbul 29 Mayıs Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Elmalıkent Mah. Elmalıkent Cad. No:4, 34764 Ümraniye/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 18,
    universite: "İstanbul Beykent Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Hadımköy -  Yerleşkesi, Akçaburgaz Mahallesi, Hadımköy İstanbul Cd. No:2/A Esenyurt / İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "1101 - Üniversiteyi Anlamak ve Eleştirel Düşünce",
        "1101 - İngilizcede Eleştirel Okuma ve Yazma",
        "1101 - Sosyal Bilimlere Giriş",
        "1211 - Genel Muhasebe",
        "1199 - Kariyer Planlama ve Yönetim Bilişim Sistemlerine Giriş",
        "1101 - Hukukun Temelleri",
        "1101 - Sosyal Bilimler İçin Matematik",
        "1101 - Türkçe Eleştirel Okuma ve Yazma",
        "1132 - Modern Dünyanın Oluşumu",
        "1101 - Siyaset Bilimine Giriş",
        "1120 - Ekonominin Esasları",
        "1212 - Programlamaya Giriş",
        "Seçmeli Ders Grubu 1",
      ],
      grade_2: [
        "1609 - İş İngilizcesi",
        "1101 - Atatürk İlkeleri İnkılap Tarihi ve Modern Türkiye'nin Oluşumu",
        "1201 - Yönetim ve Organizasyon",
        "1205 - Karar Verme Teknikleri",
        "1201 - Sosyal Bilimler İçin İstatistik",
        "1251 - Veri Yapıları ve Algoritmalar",
        "1128 - Küreselleşme",
        "1202 - Sosyal Bilimler İçin Araştırma Yöntemleri",
        "1224 - İstemci Taraflı Programlama",
        "1257 - Nesne Tabanlı Programlama",
        "1408 - Bilgi Yönetimi",
        "Seçmeli Ders Grubu 2",
      ],
      grade_3: [
        "1423 - Sunucu Taraflı Programlama",
        "1209 - İş Analizi ve Tasarımı",
        "1303 - İnsan Kaynakları Yönetimi",
        "1221 - Görsel Programlama",
        "1359 - Sistem Analizi ve Tasarımı",
        "1401 - Staj I",
        "1206 - Finansal Yönetim",
        "1612 - ERP ve Uygulamaları",
        "1601 - Yöneylem Araştırması ve Optimizasyon Teknikleri",
        "1209 - Yapısal Programlama",
        "1254 - Veritabanı Yönetim Sistemleri",
        "Seçmeli Ders Grubu 3",
      ],
      grade_4: [
        "1402 - Staj II",
        "1404 - Bilişim Sistemleri Stratejisi ve Yönetimi",
        "7. Yarıyıl Seçmeli Ders Grubu (1-6)",
        "8. Yarıyıl Seçmeli Ders Grubu (1-4)",
      ],
    },
  },
  {
    id: 19,
    universite: "Üsküdar Üniversitesi",
    fakulte: "Mühendislik ve Doğa Bilimleri Fakültesi",
    fakulte_adresi:
      "Merkez Yerleşke, Altunizade Mah. Haluk Türksoy Sk. No:14, 34662 Üsküdar/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YBS101 - Yönetim Bilişim Sistemlerine Giriş",
        "RPSI109 - Pozitif Psikoloji ve İletişim Becerileri",
        "YBS105 - İşletme Matematiği I",
        "YBS107 - İşletmenin Temel İlkeleri",
        "RKUL103 - Üniversite Kültürü I",
        "ATA103 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "TURK103 - Türk Dili I",
        "ING103 - İngilizce I",
        "YBS102 - Dijital Pazarlama",
        "YBS104 - İktisada Giriş",
        "YBS106 - İşletme Matematiği II",
        "FEL122 - Eleştirel Düşünce",
        "RKUL104 - Üniversite Kültürü II",
        "ATA104 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "TURK104 - Türk Dili II",
        "ING104 - İngilizce II",
      ],
      grade_2: [
        "YBS201 - Yönetim Organizasyon",
        "YBS203 - Muhasebeye Giriş",
        "YBS205 - İstatistik I",
        "YBS207 - Bilgi Teknolojileri Altyapıları",
        "YBS209 - Programlamaya Giriş",
        "YBS202 - Stratejik Yönetim",
        "YBS204 - Finansal Muhasebe",
        "YBS206 - İstatistik II",
        "RPRG104 - Girişimcilik ve Proje Kültürü",
        "Bölüm İçi/Dışı Seçmeli Ders I",
        "Bölüm İçi/Dışı Seçmeli Ders II",
      ],
      grade_3: [
        "YBS301 - Sistem Analizi ve Tasarım",
        "YBS303 - Veri Analizi",
        "YBS305 - Bilişim Etiği",
        "YBS307 - Kurumsal Sürdürülebilirlik",
        "YBS300 - Kurumsal Bilişim Sistemleri",
        "YBS302 - Web Tabanlı Programlama",
        "YBS304 - Örgütsel Psikoloji",
        "PSI242 - Psikoloji Kavram ve Yaklaşımları",
        "Bölüm İçi/Dışı Seçmeli Ders III",
        "Bölüm İçi/Dışı Seçmeli Ders IV",
      ],
      grade_4: [
        "YBS401 - Yapay Zekaya Giriş",
        "YBS403 - Mezuniyet Projesi I",
        "YBS405 - Bilişim Hukuku",
        "YBS402 - Siber Güvenlik",
        "YBS404 - Mezuniyet Projesi II",
        "Bölüm İçi/Dışı Seçmeli Ders V",
        "Bölüm İçi/Dışı Seçmeli Ders VI",
        "Bölüm İçi/Dışı Seçmeli Ders VII",
      ],
    },
  },
  {
    id: 20,
    universite: "Altınbaş Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi:
      "Gayrettepe Yerleşkesi, Büyükdere Cad. No:147 Esentepe, 34394 Şişli/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 21,
    universite: "Fenerbahçe Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi:
      "Metropol İstanbul, Atatürk Mah. Ataşehir Bulvarı, 34758 Ataşehir/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 22,
    universite: "İstanbul Kültür Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Ataköy Kampüsü, E5 Karayolu Üzeri 34158 Bakırköy/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 23,
    universite: "Doğuş Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Dudullu Yerleşkesi, Esenkent Mah. Nato Yolu Cad. No:265, 34775 Ümraniye/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 24,
    universite: "İstanbul Atlas Üniversitesi",
    fakulte: "İnsan ve Toplum Bilimleri Fakültesi",
    fakulte_adresi:
      "Vadi Kampüs, Hamidiye Mah. Anadolu Cad. No:40, 34408 Kağıthane/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "1317111001 - Bilgi Sistemleri ve Teknolojisine Giriş",
        "1317111003 - Yönetim Bilişim Sistemleri",
        "1317111005 - Yönetim İlkeleri",
        "1317111007 - Matematik I",
        "5010111005 - Kariyer Planlama",
        "5010111013 - İspanyolca I",
        "5010111015 - Türk Dili",
        "1300121004 - Hukuka Giriş",
        "1317121002 - Algoritmik Düşünme ve Tasarım",
        "1317121004 - İktisada Giriş",
        "1317121006 - Matematik II",
        "5010111002 - Atatürk İlkeleri ve İnkılap Tarihi",
        "5010111014 - İspanyolca II",
      ],
      grade_2: [
        "1300211005 - Yönetim Muhasebesi",
        "1300211007 - Sosyal Bilimler için Araştırma Yöntemleri",
        "1317211001 - Programlama I",
        "1317211003 - İstatistik I",
        "1317211005 - Veri Yapıları ve Yönetimi",
        "1317211007 - Bilgisayar Donanımı ve Sistemi Yazılımı",
        "1317211009 - Bilişim Hukuku",
        "1317221002 - Yönetim ve Organizasyon",
        "1317221004 - Programlama II",
        "1317221006 - E-Ticaret",
        "1317221008 - İstatistik II",
        "1317221010 - Veritabanı Sistemlerine Giriş",
        "1317221012 - Pazarlama İlkeleri",
        "Üniversite Seçmeli",
      ],
      grade_3: [
        "1317311001 - Web Tasarım ve Programlama",
        "1317311003 - Gelişmiş Veritabanları",
        "1317311005 - İş Zekası ve Veri Madenciliği",
        "1317321002 - İşletmeler için Karar Destek Sistemleri",
        "1317321004 - Makine Öğrenimi",
        "1317321006 - Bilgi Sistemleri Proje Yönetimi",
        "Üniversite Seçmeli",
        "Department Elective I",
        "Department Elective II",
        "Department Elective III",
        "Department Elective IV",
        "Department Elective V",
      ],
      grade_4: [
        "1317411001 - Girişimcilik ve İnovasyon",
        "1317411003 - Yaz Stajı",
        "1317411005 - Yapay Zekanın Temelleri",
        "1317411007 - Mezuniyet Projesi I",
        "1317421002 - Mezuniyet Projesi II",
        "1317421004 - Bilgisayar Ağları",
        "1317421006 - Dijital Dönüşüm ve Değişim Yönetimi",
        "Department Elective VI",
        "Department Elective VII",
        "Department Elective VIII",
        "Department Elective IX",
        "Department Elective X",
      ],
    },
  },
  {
    id: 25,
    universite: "İstanbul Topkapı Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi:
      "Kazlıçeşme Yerleşkesi, Kazlıçeşme Mah. Abay Cad. No:12, 34020 Zeytinburnu/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "FCS101 - Temel Bilgi Teknolojileri",
        "FCS103 - Hukukun Temel İlkeleri",
        "FCS107 - İktisadın Temel İlkeleri",
        "FCS109 - Matematik",
        "MIS105 - Yönetim Bilişim Sistemleri",
        "MIS107 - Algoritmaya ve Programlamaya Giriş",
        "URC101 - İngilizce",
        "URC113 - Türk Dili I",
        "FCS102 - Bilgi Teknolojileri Kullanımı",
        "FCS106 - İşletmenin Temel İlkeleri",
        "FCS108 - İstatistik",
        "MIS102 - Ayrık Matematik",
        "MIS106 - Programlama",
        "URC110 - Kariyer Planlama",
        "URC114 - Türk Dili II",
      ],
      grade_2: [
        "MIS201 - Veri Yapısı ve Veritabanı Yönetim Sistemleri",
        "MIS207 - Web Dizaynı ve İnternet Programlama",
        "MIS209 - Pazarlama Yönetimi",
        "URC209 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "Bölüm Seçmeli I",
        "Bölüm Seçmeli II",
        "MIS204 - Muhasebe ve Finans",
        "MIS206 - Nesne Yönelimli Programlama",
        "MIS208 - Sistem Analizi ve Dizaynı",
        "URC210 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "Bölüm Seçmeli III",
        "Bölüm Seçmeli IV",
      ],
      grade_3: [
        "MIS307 - Operasyon Yönetimi",
        "MIS309 - Bilgisayar Ağları",
        "MIS311 - Görsel Programlama",
        "Bölüm Seçmeli V",
        "Üniversite Seçmeli I",
        "MIS308 - Araştırma Yöntemleri ve Analitik",
        "MIS310 - İleri Programlama",
        "Bölüm Seçmeli VI",
        "Bölüm Seçmeli VII",
        "Fakülte Seçmeli I",
      ],
      grade_4: [
        "MIS409 - Proje Yönetimi",
        "MIS411 - Staj",
        "Bölüm Seçmeli VIII",
        "Bölüm Seçmeli IX",
        "Fakülte Seçmeli II",
        "MIS408 - Endüstri 4.0 ve Uygulamaları",
        "Bölüm Seçmeli X",
        "Bölüm Seçmeli XI",
        "Bölüm Seçmeli XII",
        "Bölüm Seçmeli XIII",
        "Fakülte Seçmeli III",
      ],
    },
  },
  {
    id: 26,
    universite: "İstanbul Nişantaşı Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi:
      "NeoTech Kampüs, Maslak Mah. Taşyoncası Sok. No: 1V ve No:1Y, 34398 Sarıyer/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 27,
    universite: "İstanbul Gelişim Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi:
      "Gelişim Tower, Cihangir Mah. Petrol Ofisi Cad. No:5, 34310 Avcılar/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "EATA191 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "EEKO101 - Ekonomiye Giriş",
        "EISL121 - Hukuka Giriş",
        "EISL125 - İşletmeye Giriş",
        "ETRD101 - Türk Dili I",
        "EUTI121 - Temel Matematik",
        "EYDL191 - İngilizce I",
        "EATA192 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "EEKO112 - Makro Ekonomi",
        "EISL104 - Genel Muhasebe",
        "EISL124 - Temel İstatistik",
        "ETRD102 - Türk Dili II",
        "EYDL192 - İngilizce II",
        "EYON110 - Yapay Zeka, Algoritma ve Programlama",
      ],
      grade_2: [
        "EEKO209 - Sosyal Bilimlerde Araştırma Yöntemleri",
        "EISL223 - Yönetim ve Organizasyon",
        "EYDL291 - Mesleki İngilizce",
        "EYON203 - Sistem Analizi ve Tasarımı",
        "EYON221 - Yapısal Programlama",
        "GE Seçmeli Ders Grubu (3. YY)",
        "EBLG220 - Nesne Yönelimli Programlama",
        "EUTI220 - Pazarlama Yönetimi",
        "EYON206 - Veri Tabanı ve Uygulamaları",
        "EYON212 - Javaya Giriş",
        "GE Seçmeli Ders Grubu (4. YY)",
      ],
      grade_3: [
        "EYON303 - Yönetim Bilişim Sistemleri",
        "EYON315 - Veri Analitiği",
        "İİSBF YBS 5. YY. Seçmeli Ders Grubu",
        "GE Seçmeli Ders Grubu (5. YY)",
        "Üniversite Seçmeli Ders (5. YY)",
        "EBLG350 - Veri Madenciliği",
        "EYON320 - İleri Veri Tabanı Uygulamaları",
        "İİSBF YBS 6. YY. Seçmeli Ders Grubu",
        "GE Seçmeli Ders Grubu (6. YY)",
        "KEP I - İngilizce",
        "Üniversite Seçmeli Ders (6. YY)",
      ],
      grade_4: [
        "EYON413 - Bilişim Etiği",
        "EYON421 - Siber Güvenlik",
        "İİSBF YBS 7. YY. Seçmeli Ders Grubu",
        "GE Seçmeli Ders Grubu (7. YY)",
        "KEP II - İngilizce",
        "Üniversite Seçmeli Ders (7. YY)",
        "8. YY İMU Seçmeli Dersleri (İş Başında Mesleki Uygulamalar / Bitirme Tezi)",
      ],
    },
  },
  {
    id: 28,
    universite: "İstanbul Gedik Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi:
      "Kartal Yerleşkesi, Cumhuriyet Mah. E-5 Yanyol No:29, 34876 Kartal/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "ATA101 - Atatürk İlkeleri ve İnkılâp Tarihi I",
        "BİL102 - Bilişim ve İletişim Uygulamaları",
        "IK101 - Kariyer Planlama",
        "ING101 - İngilizce I",
        "TUR101 - Türk Dili I",
        "UNIV101 - Üniversite Hayatına Giriş",
        "YBS103 - İşletmeye Giriş",
        "YBS105 - Bilişim Hukuku",
        "ATA102 - Atatürk İlkeleri ve İnkılâp Tarihi II",
        "ING102 - İngilizce II",
        "TUR102 - Türk Dili II",
        "YBS102 - Bilgisayar Programlamaya Giriş",
        "YBS104 - Yönetim ve Organizasyon",
        "YBS106 - Matematik",
        "YBS108 - Algoritma Geliştirme",
      ],
      grade_2: [
        "YBS201 - Pazarlama Yönetimi",
        "YBS211 - Nesne Yönelimli Programlama",
        "YBS221 - İstatistik",
        "YBS231 - Veri Yapıları ve Algoritma",
        "YBS241 - Bilişim Sistemleri ve Teknolojileri",
        "YBS202 - Bilgisayarlı Muhasebe",
        "YBS204 - Veri Tabanı Yönetim Sistemleri",
        "YBS212 - E-Ticaret",
        "YBS222 - Örgütsel Davranış",
        "YBS232 - Görsel Programlama",
      ],
      grade_3: [
        "ÜNİ081 - İnsan Kaynakları Yönetimi",
        "YBS301 - Sistem Analizi ve Tasarımı",
        "YBS311 - Mobil Programlama",
        "YBS321 - Stratejik Yönetim ve İşletme Politikası",
        "YBS331 - İnovasyon Yönetimi",
        "YBS333 - Girişimcilik",
        "Bölüm Seçmeli I",
        "Disiplinlerarası Seçmeli I",
        "YBS312 - Veri Madenciliği",
        "YBS322 - Proje Yönetimi",
        "YBS324 - İnternet Programlama",
        "Bölüm Seçmeli II",
        "Disiplinlerarası Seçmeli II",
      ],
      grade_4: [
        "ÜNİ082 - Öğrenmeyi Öğrenme",
        "Bölüm Seçmeli III",
        "Bölüm Seçmeli IV",
        "Bölüm Seçmeli V",
        "Bölüm Seçmeli VI",
        "Disiplinlerarası Seçmeli III",
        "YBS402 - Bitirme Projesi",
        "Bölüm Seçmeli VII",
        "Bölüm Seçmeli VIII",
        "Disiplinlerarası Seçmeli IV",
        "Disiplinlerarası Seçmeli V",
      ],
    },
  },
  {
    id: 29,
    universite: "İstanbul Galata Üniversitesi",
    fakulte: "Sanat ve Sosyal Bilimler Fakültesi",
    fakulte_adresi:
      "Frej Han Yerleşkesi, Bereketzade Mah. Şair Ziya Paşa Cad. No:14 34421 Beyoğlu/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 30,
    universite: "İstanbul Arel Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Kemal Gözükara Yerleşkesi, Türkoba Mah. Erguvan Sk. No:26, 34537 Tepekent-Büyükçekmece/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 31,
    universite: "Demiroğlu Bilim Üniversitesi",
    fakulte: "Fen-Edebiyat Fakültesi",
    fakulte_adresi: "Büyükdere Cad. No:120, 34394 Esentepe-Şişli/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "ORTL101 - Yüksek Öğrenime Giriş",
        "ORTL161 - Atatürk İlkeleri ve İnkılap Tarihi-I",
        "ORTL171 - Türk Dili-I",
        "MBBL041 - Temel Matematik",
        "YDLL161 - İngilizce I",
        "ISLL109 - Mikro İktisat",
        "ISLL103 - İşletmeye Giriş",
        "YBSL172 - Bilişim Sistemleri ve Teknolojileri",
        "ORTL261 - Atatürk İlkeleri ve İnkılap Tarihi-II",
        "ORTL271 - Türk Dili-II",
        "YDLL162 - İngilizce II",
        "ISLL116 - Makro İktisat",
        "ISLL114 - İstatistik",
        "ISLL238 - Örgütlerin Yönetimi",
        "YBSL182 - Algoritma ve Programlama",
      ],
      grade_2: [
        "YDLL261 - İngilizce III",
        "MBBL061 - Bilgi Teknolojileri Kullanımı",
        "YBSL184 - İşletim Sistemleri",
        "ISLL201 - Finansal Muhasebe-I",
        "ISLL221 - Pazarlama İlkeleri",
        "YBSL274 - Problem Çözme ve Karar Alma Teknikleri",
        "YBSL272 - Veri Bilimi",
        "YDLL262 - İngilizce IV",
        "ISLL202 - Finansal Muhasebe-II",
        "YBSL282 - Web Uygulamaları ve Programlama",
        "YBSL284 - Bulut Bilişim",
        "YBSL286 - Bilişim Hukuku",
        "YBSL288 - Veri Tabanı Yönetim Sistemleri",
        "YBSL290 - Sistem Analizi ve Tasarımı",
      ],
      grade_3: [
        "YDLL311 - Mesleki İngilizce I",
        "21.yy Yetkinlikleri Seçmeli I",
        "Bölüm Seçmeli 1",
        "Bölüm Seçmeli 2",
        "YBSL372 - Karar Destek Sistemleri",
        "YBSL374 - İşletmelerde Ağ Yönetimi ve Güvenliği",
        "YBSL376 - İşletme Bilgi Sistemleri Analiz ve Tasarımı",
        "YDLL313 - Mesleki İngilizce II",
        "21.yy Yetkinlikleri Seçmeli II",
        "Bölüm Seçmeli 3",
        "Bölüm Seçmeli 4",
        "YBSL382 - Algoritma Geliştirme ve Programlama",
        "YBSL384 - Sosyal Medya ve Web Analizi",
        "YBSL386 - Müşteri İlişkileri ve Tedarik Zinciri Yönetimi",
        "YBSL388 - Veri Madenciliği",
      ],
      grade_4: [
        "YDLL315 - Mesleki İngilizce III",
        "Bölüm Seçmeli 5",
        "Bölüm Seçmeli 6",
        "Üniversite Seçmeli I",
        "YBSL472 - İşletmelerde İş Zekası ve Uygulamaları",
        "YBSL474 - Nesne Yönelimli Programlama",
        "YBSL476 - Bilişim Sistemleri Proje Analizi",
        "21.yy Yetkinlikleri Seçmeli III",
        "Bölüm Seçmeli 7",
        "Üniversite Seçmeli II",
        "YBSL482 - Proje Tasarımı ve Geliştirme",
        "YBSL484 - Uzman Sistemler ve Yapay Zeka Sistemleri",
        "YBSL420 - Yönetim Bilişim Sistemleri Stajı",
      ],
    },
  },
  {
    id: 32,
    universite: "İstanbul Esenyurt Üniversitesi",
    fakulte: "İşletme ve Yönetim Bilimleri Fakültesi",
    fakulte_adresi:
      "Zafer Mah. Adile Naşit Bulvarı No:1, 34513 Esenyurt/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "2075G1002 - Türk Dili I",
        "2075G1003 - Yabancı Dil I (İngilizce)",
        "20B1001 - Matematik I",
        "2021G1001 - Yönetim Bilişim Sistemlerine Giriş",
        "20G2007 - Temel Hukuk",
        "2021G1002 - Algoritma ve Programlama 1",
        "2075B1002 - Türk Dili II",
        "2075B1003 - Yabancı Dil II (İngilizce)",
        "20B1001 - Matematik II",
        "2021B1001 - Bilişim Sistemleri için Strateji, Yönetim ve Kazanım",
        "2075B1010 - Girişimcilik ve Kariyer Planlama",
        "2021B1003 - Algoritma ve Programlama 2",
      ],
      grade_2: [
        "2075G1001 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "2021B2021 - Davranış Bilimleri",
        "2021G2002 - Veri Yapıları",
        "2021G2003 - İstatistik ve Olasılık",
        "20G1010 - İşletmeye Giriş",
        "2021B2004 - Finansal Yönetim",
        "2075B1001 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "2021B1001 - Yönetim ve Organizasyon",
        "2021B2002 - Veritabanı Yönetim Sistemleri",
        "2021B2003 - İstatistik Analiz",
        "20B2003 - Pazarlama Yönetimi",
        "2021G2006 - Sürdürülebilirlik Yönetimi",
      ],
      grade_3: [
        "2021G3001 - Yöneylem Araştırması I",
        "2021B3002 - Web Programlama",
        "2021B3001 - Yöneylem Araştırması II",
        "2021G3002 - Nesneye Dayalı Programlama",
        "Bölüm Seçmeli 1",
        "Bölüm Seçmeli 2",
        "Fakülte Seçmeli 1",
        "Fakülte Seçmeli 2",
        "Üniversite Seçmeli 1",
        "Üniversite Seçmeli 2",
      ],
      grade_4: [
        "İşletim Sistemleri",
        "2021G4002 - Veri Madenciliği",
        "2021G4010 - Excel VBA Programlama",
        "2021B4008 - Proje Yönetimi",
        "Siber Güvenlik",
        "2021B4009 - Yapay Zeka",
        "Bölüm Seçmeli 3",
        "Bölüm Seçmeli 4",
        "Fakülte Seçmeli 3",
        "Fakülte Seçmeli 4",
      ],
    },
  },
  {
    id: 33,
    universite: "Fatih Sultan Mehmet Vakıf Üniversitesi",
    fakulte: "İktisadi, İdari ve Sosyal Bilimler Fakültesi",
    fakulte_adresi:
      "Haliç Yerleşkesi, Sütlüce Mah. Karaağaç Cad. No:12, 34445 Beyoğlu/İstanbul",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "MGT22101E - Introduction to Business / İşletmeye Giriş",
        "MGT22102E - Introduction to Microeconomics / Mikroekonomiye Giriş",
        "MGT22104E - Mathematics for Business I / İşletme Matematiği I",
        "POLS22103E - Introduction to Sociology / Sosyolojiye Giriş",
        "MIS24101E - Programming and Algorithms I / Programlama ve Algoritmalar I",
        "POLS22107E - Academic Writing / Akademik Yazım",
        "FSM22OSDA01 - Joint Elective Course (Group A)",
        "MIS24103E - Introduction to Management Information Systems / Yönetim Bilişim Sistemlerine Giriş",
        "MGT22103E - Introduction to Macroeconomics / Makroekonomiye Giriş",
        "MGT22105E - Mathematics for Business II / İşletme Matematiği II",
        "MIS24102E - Programming and Algorithms II / Programlama ve Algoritmalar II",
        "POLS22101E - Introduction to Political Science / Siyaset Bilimine Giriş",
        "POLS22108E - Textual Analysis and Effective Communication / Metin Analizi ve Etkin İletişim",
        "FSM22OSDA02 - Joint Elective Course (Group A)",
      ],
      grade_2: [
        "MGT22201E - Introduction to Statistics / İstatistiğe Giriş",
        "MGT22203E - Financial Accounting / Finansal Muhasebe",
        "MGT22205E - Business Communication / İş İletişimi",
        "POLS22109E - Introduction to Law / Hukuka Giriş",
        "MIS24201E - Introduction to Data Base / Veritabanına Giriş",
        "FSM22OSDA03 - Joint Elective Course (Group A)",
        "MGT22202E - Statistical Analysis / İstatistiksel Analiz",
        "MGT22204E - Managerial Accounting / Yönetim Muhasebesi",
        "MGT22208E - Business Law / İşletme Hukuku",
        "MIS24202E - Object Oriented Programming / Nesne Yönelimli Programlama",
        "MIS24204E - Computer Hardware and System Software / Bilgisayar Donanımı ve Sistem Yazılımı",
        "FSM22OSDA04 - Joint Elective Course (Group A)",
      ],
      grade_3: [
        "MGT22305E - Operations Management / Yöneylem Yönetimi",
        "MGT22303E - Marketing Management / Pazarlama Yönetimi",
        "MGT22301E - Financial Management / Finansal Yönetim",
        "MIS24301E - Web Based Application / Web Tabanlı Uygulama",
        "MIS24ÜSD01 - University Elective Course I",
        "FSM22OSDB01 - Joint Elective Course (Group B)",
        "MIS24302E - Data Mining / Veri Madenciliği",
        "MIS24304E - Business Application Development / İş Uygulaması Geliştirme",
        "MIS24ÜSD02 - University Elective Course II",
        "MIS24ÜSD03 - University Elective Course III",
        "MIS24ÜSD04 - University Elective Course IV",
        "FSM22OSDB02 - Joint Elective Course (Group B)",
      ],
      grade_4: [
        "MIS24401E - Internship (25 work days) / Staj",
        "MGT22401E - Strategic Management / Stratejik Yönetim",
        "MIS24ÜSD05 - University Elective Course V",
        "MIS24ÜSD06 - University Elective Course VI",
        "MIS24ÜSD07 - University Elective Course VII",
        "FSM22OSDB03 - Joint Elective Course (Group B)",
        "MGT22402E - Innovation and Entrepreneurship / Yenilik ve Girişimcilik",
        "MIS24ÜSD08 - University Elective Course VIII",
        "MIS24ÜSD09 - University Elective Course IX",
        "MIS24ÜSD10 - University Elective Course X",
        "FSM22OSDB04 - Joint Elective Course (Group B)",
      ],
    },
  },
];
