import { temelYBSDersleri } from "./temelybs";

export const karadenizYbs = [
  // ================= KARADENİZ BÖLGESİ =================
  {
    id: 74,
    universite: "Karadeniz Teknik Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Kanuni Kampüsü, 61080 Ortahisar/Trabzon",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YBS1XXX - Introduction to Algorithms and Programming / Algoritma ve Programlamaya Giriş",
        "YBS1005 - Introduction to Management Information Systems / Yönetim Bilişim Sistemlerine Giriş",
        "AITB1001 - Atatürk's Principles and History of Turkish Revolution-I / Atatürk İlkeleri ve İnkılap Tarihi-I",
        "YDB1001 - English-I / İngilizce-I",
        "YBS1XXX - Mathematics / Matematik",
        "TDB1001 - Turkish Language-I / Türk Dili-I",
        "YBS1XXX - Introduction to Business / İşletmeciliğe Giriş",
        "ISL1001 - Basic Concepts of Law / Hukukun Temel Kavramları",
        "YBS1XXX - Statistics / İstatistik",
        "YBS1XXX - Basic Programming / Temel Programlama",
        "YBS1XXX - Basic Information Technologies / Temel Bilgi Teknolojileri",
        "TDB1000 - Turkish Language-II / Türk Dili-II",
        "AITB1000 - Atatürk's Principles and History of Turkish Revolution-II / Atatürk İlkeleri ve İnkılap Tarihi-II",
        "YDB1004 - English-II / İngilizce-II",
        "YBS1XXX - Business Management / İşletme Yönetimi",
        "IKT1005 - Introduction to Economics / İktisada Giriş",
      ],
      grade_2: [
        "YBS2017 - Research Methods / Araştırma Yöntemleri",
        "YBS2XXX - Occupational Health and Safety / İş Sağlığı ve Güvenliği",
        "YBS2001 - Vocational English / Mesleki İngilizce",
        "YBS2XXX - Object Oriented Programming / Nesne Tabanlı Programlama",
        "Departmental Elective I / Bölüm Seçmeli Dersi I",
        "Departmental Elective II / Bölüm Seçmeli Dersi II",
        "YBS2002 - Database Management Systems / Veri Tabanı Yönetim Sistemleri",
        "YBS2XXX - Data Science Programming / Veri Bilimi Programlama",
        "YBS2XXX - Computer Networks and Security / Bilgisayar Ağları ve Güvenlik",
        "Departmental Elective III / Bölüm Seçmeli Dersi III",
        "Departmental Elective IV / Bölüm Seçmeli Dersi IV",
      ],
      grade_3: [
        "YBS3XXX - Visual User Interface Design and Programming / Görsel Ara Yüz Tasarımı ve Programlama",
        "YBS3XXX - Operations Research / Yöneylem Araştırması",
        "YBS3XXX - Artificial Intelligence I / Yapay Zekâ I",
        "YBS3XXX - Systems Analysis and Design / Sistem Analizi ve Tasarımı",
        "Departmental Elective V / Bölüm Seçmeli Dersi V",
        "Departmental Elective VI / Bölüm Seçmeli Dersi VI",
        "YBS3XXX - Strategic Management / Stratejik Yönetim",
        "YBS3XXX - Decision Support Systems / Karar Destek Sistemleri",
        "YBS3XXX - Artificial Intelligence II / Yapay Zekâ II",
        "YBS3XXX - Production Management / Üretim Yönetimi",
        "Departmental Elective VII / Bölüm Seçmeli Dersi VII",
        "Departmental Elective VIII / Bölüm Seçmeli Dersi VIII",
      ],
      grade_4: [
        "YBS4XXX - Enterprise Resource Planning (ERP) / Kurumsal Kaynak Planlaması",
        "YBS4XXX - Business Intelligence and Data Mining / İş Zekası ve Veri Madenciliği",
        "YBS4XXX - Project Management / Proje Yönetimi",
        "Departmental Elective IX, X, XI / Bölüm Seçmeli Dersleri IX, X, XI",
        "YBS4XXX - Workplace Practice / İş Yeri Uygulaması (Full Semester)",
      ],
    },
  },
  {
    id: 75,
    universite: "Düzce Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi: "Konuralp Yerleşkesi, 81620 Merkez/Düzce",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 76,
    universite: "Bartın Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi: "Ağdacı Kampüsü, 74100 Merkez/Bartın",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "TDİ101 - Turkish Language I / Türk Dili I",
        "ATA 101 - Atatürk's Principles and History of Turkish Revolution I / Atatürk İlkeleri ve İnkılap Tarihi I",
        "ENF181 - Basic Information Technology Usage / Temel Bilgi Teknolojileri Kullanımı",
        "YDİ101 - Foreign Language I / Yabancı Dil I",
        "YBS109 - Mathematics I / Matematik I",
        "YBS113 - University Culture / Üniversite Kültürü",
        "YBS117 - Introduction to Business Science / İşletme Bilimine Giriş",
        "YBS119 - Accounting I / Muhasebe I",
        "YBS121 - Economics I / İktisat I",
        "YBS123 - Basic Concepts of Law / Hukukun Temel Kavramları",
        "ATA102 - Atatürk's Principles and History of Turkish Revolution II / Atatürk İlkeleri ve İnkılap Tarihi II",
        "ENF182 - Basic Computer Sciences / Temel Bilgisayar Bilimleri",
        "TDİ102 - Turkish Language II / Türk Dili II",
        "YBS102 - Introduction to Programming (QBASIC) / Programlamaya Giriş",
        "YBS112 - Mathematics II / Matematik II",
        "YBS114 - Accounting II / Muhasebe II",
        "YBS116 - Business Management / İşletme Yönetimi",
        "YBS118 - Economics II / İktisat II",
        "YDİ102 - Foreign Language II / Yabancı Dil II",
      ],
      grade_2: [
        "YBS203 - Management and Organization / Yönetim ve Organizasyon",
        "YBS207 - Data Structures and Algorithms / Veri Yapıları ve Algoritmalar",
        "YBS209 - Management Information Systems / Yönetim Bilişim Sistemleri",
        "YBS211 - Research Methods in Social Sciences / Sosyal Bilimlerde Araştırma Yöntemleri",
        "YBS213 - Statistics I / İstatistik I",
        "YBS215 - Principles of Marketing / Pazarlama İlkeleri",
        "YBS206 - Contemporary Management Techniques / Çağdaş Yönetim Teknikleri",
        "YBS208 - Human Resources Management / İnsan Kaynakları Yönetimi",
        "YBS210 - System Analysis and Design / Sistem Analizi ve Tasarım",
        "YBS212 - Database Management System / Veri Tabanı Yönetim Sistemi",
        "YBS214 - Statistics II / İstatistik II",
        "YBS216 - Financial Management / Finansal Yönetim",
      ],
      grade_3: [
        "YBS301 - Operations Research I / Yöneylem Araştırması I",
        "YBS303 - Visual Programming (Delphi) / Görsel Programlama",
        "YBS305 - Web Design and Internet Programming / Web Tasarımı ve İnternet Programlama",
        "YBS307 - Computer Hardware and System Software / Bilgisayar Donanımı ve Sistem Yazılımı",
        "YBS302 - Operations Research II / Yöneylem Araştırması II",
        "YBS306 - IT Project Management / Bilişim Projesi Yönetimi",
        "YBS308 - IT Law and Ethics / Bilişim Hukuku ve Etiği",
        "YBS310 - Production Management / Üretim Yönetimi",
      ],
      grade_4: [
        "YBS401 - E-Commerce and E-Government / E-Ticaret ve E-Devlet",
        "YBS403 - Decision Support Systems / Karar Destek Sistemleri",
        "YBS405 - Object Oriented Programming (C#) / Nesne Tabanlı Programlama",
        "YBS402 - Supply Chain and Logistics Management / Tedarik Zinciri ve Lojistik Yönetimi",
        "YBS404 - Data Mining / Veri Madenciliği",
        "YBS406 - Data Communications and Computer Networks / Veri İletişimi ve Bilgisayar Ağları",
        "Elective Courses / Seçmeli Dersler (Big Data, Machine Learning, Deep Learning, R with Data Science, etc.)",
      ],
    },
  },
  {
    id: 77,
    universite: "Gümüşhane Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Bağlarbaşı Mah. Gümüşhane Üni. Kampüsü, 29100 Merkez/Gümüşhane",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "MAT 118 - Mathematics-II / Matematik-II",
        "IKT 102 - General Economics / Genel Ekonomi",
        "YDB 116 - English-II / İngilizce-II",
        "AITB 192 - Atatürk's Principles and History of Turkish Revolution-II / Atatürk İlkeleri ve İnkılap Tarihi-II",
        "TDB 102 - Turkish Language-II / Türk Dili-II",
        "YBS 104 - Office Automation Systems / Ofis Otomasyon Sistemleri",
        "YBS 106 - Management and Organization / Yönetim ve Organizasyon",
        "KRY 102 - Career Planning / Kariyer Planlama",
      ],
      grade_2: [
        "YBS 208 - Database Management Systems / Veri Tabanı Yönetim Sistemleri",
        "YBS 204 - Statistics-II / İstatistik-II",
        "YBSSEC 214 - Natural Language Processing / Doğal Dil İşleme (Elective)",
        "YBSSEC 206 - Technology and Innovation Management / Teknoloji ve Yenilik Yönetimi (Elective)",
        "YBS 210 - Financial Management / Finansal Yönetim",
        "YBS 206 - Management Information Systems / Yönetim Bilgi Sistemleri",
        "YBSSEC 212 - Vocational English-II / Mesleki İngilizce-II (Elective)",
      ],
      grade_3: [
        "YBS 310 - Visual Programming / Görsel Programlama",
        "YBSSEC 316 - Organizational Behaviour / Örgütsel Davranış (Elective)",
        "YBSSEC 308 - Data Mining Applications / Veri Madenciliği Uygulamaları (Elective)",
        "YBSSEC 312 - Python Applications / Python Uygulamaları (Elective)",
        "YBS 304 - Operations Research-II / Yöneylem-II",
        "YBS 308 - Internet and Web Applications / İnternet ve Web Uygulamaları",
      ],
      grade_4: [
        "TEZ 400 - Graduation Thesis / Bitirme Çalışması",
        "YBSSEC 406 - R Programming / R Programlama (Elective)",
        "YBS 402 - Artificial Intelligence / Yapay Zeka",
        "YBSSEC 410 - Industry 4.0 / Endüstri 4.0 (Elective)",
        "YBSSEC 408 - Effective Presentation Techniques / Etkili Sunum Teknikleri (Elective)",
      ],
    },
  },
  {
    id: 78,
    universite: "Bayburt Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Babasultan Yerleşkesi, İmaret Tepe Mevkii, 69000 Merkez/Bayburt",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "YÖN109B - General Economics / Genel Ekonomi",
        "YÖN111B - General Business / Genel İşletme",
        "YÖN113B - Introduction to Management Information Systems / Yönetim Bilişim Sistemlerine Giriş",
        "YÖN107B - Mathematics I / Matematik I",
        "YÖN109 - Introduction to Computer and Information Processing / Bilgisayara Giriş ve Bilgi İşleme",
        "YÖN115B - Digital Literacy / Dijital Okur Yazarlık",
        "YÖN112B - Marketing / Pazarlama",
        "YÖN112 - Database Systems and Applications / Veri Tabanı Sistemleri ve Uygulamaları",
        "YÖN110 - Introduction to Web Design / WEB Tasarımına Giriş",
        "YÖN114 - Management and Organization / Yönetim ve Organizasyon",
        "YÖN116 - Introduction to Graphic Design / Grafik Tasarımına Giriş",
        "YÖN108B - Mathematics II / Matematik II",
      ],
      grade_2: [
        "YÖN203 - Introduction to Algorithm and Programming / Algoritma ve Programlamaya Giriş",
        "YÖN205B - General Accounting / Genel Muhasebe",
        "YÖN201B - Statistics I / İstatistik I",
        "YÖN203B - Database Systems and Applications I / Veri Tabanı Sistemleri ve Uygulamaları I",
        "YÖN208 - Web Programming (Java) / WEB Programlama (Java)",
        "YÖN204 - Advanced Database Applications / İleri Veri Tabanı Uygulamaları",
        "YÖN202 - Advanced Statistics / İleri İstatistik",
        "YÖN206 - Management Accounting / Yönetim Muhasebesi",
        "YÖN208B - Visual Programming / Görsel Programlama",
        "YÖN212 - Internship / STAJ",
      ],
      grade_3: [
        "YÖN301 - Data Mining / Veri Madenciliği",
        "YÖN303 - Advanced Web Design / İleri WEB Tasarımı",
        "YÖN309 - Object Oriented Programming (Modeling) / Nesne Yönelimli Programlama (Modelleme)",
        "YÖN307 - Cyber Law / Siber Hukuk",
        "YÖN305 - Organizational Behavior / Örgütsel Davranış",
        "YÖN308 - System Analysis and Design / Sistem Analizi ve Tasarımı",
        "YÖN302 - Information Security and Ethics / Bilgi Güvenliği ve Etik",
        "YÖN304 - Developing Business Applications / İşletme Uygulaması Geliştirme",
        "YÖN306 - E-Business / Elektronik İşletmecilik",
        "YÖN310.1 - Mobile Programming and Development / Mobil Programlama ve Geliştirme (Elective)",
      ],
      grade_4: [
        "YÖN401 - Project Management / Proje Yönetimi",
        "YÖN403 - Decision Support Systems in Business / İşletmelerde Karar Destek Sistemi",
        "YÖN405 - Customer Relationship Management / Müşteri İlişkileri Yönetimi",
        "YÖN407.3 - Corporate Information Systems / Kurumsal Bilgi Sistemleri (Elective)",
        "YÖN402 - Project / Proje",
        "YÖN404 - Supply Chain Management / Tedarik Zinciri Yönetimi",
        "YÖN410B - Cloud Computing / Bulut Bilişim",
        "YÖN412B.6 - Blockchain Technology and Applications / Blokzincir Teknolojisi ve Uygulamaları (Elective)",
        "YÖN402B - Graduation Project / Bitirme Projesi",
      ],
    },
  },
];
