import { temelYBSDersleri } from "./temelybs";

export const marmaraYbs = [
  // ================= MARMARA BÖLGESİ (DİĞER) =================
  {
    id: 53,
    universite: "Sakarya Üniversitesi",
    fakulte: "İşletme Fakültesi",
    fakulte_adresi:
      "Esentepe Kampüsü, Kemalpaşa Mah. Üniversite Cad. 54050 Serdivan/Sakarya",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "TUR 101 - Türk Dili",
        "UNI 101 - Üniversite Yaşamına Giriş",
        "YBS 107 - Genel Matematik",
        "IKT 101 - İktisada Giriş",
        "YBS 103 - Bilişim Sistemlerine Giriş",
        "ISL 101 - İşletme Bilimine Giriş",
        "YBS 105 - Yazılı ve Sözlü İletişim Becerileri",
        "ING 190 - İngilizce",
        "ISL 122 - Hukuka Giriş",
        "ISL 102 - Genel Muhasebe",
        "YBS 102 - Algoritma ve Programlamaya Giriş",
        "YBS 106 - İşletme Matematiği",
        "ISL 104 - Yönetim ve Organizasyon",
      ],
      grade_2: [
        "ATA 201 - Atatürk İlkeleri ve İnkılâp Tarihi",
        "YBS 205 - Yöneylem Araştırması",
        "YBS 207 - Yönetim Bilişim Sistemleri",
        "YBS 251 - Araştırma Yöntemleri",
        "YBS 201 - Veri Yapıları",
        "YBS 202 - İstatistik ve Uygulamaları",
        "ISL 202 - Pazarlama Yönetimi",
        "YBS 206 - Nesneye Dayalı Modelleme ve Programlama",
        "YBS 210 - Gereksinim Yönetimine Giriş",
        "YBS 256 - Python",
        "YBS 264 - Grafik ve Animasyon",
        "Girişimcilik",
      ],
      grade_3: [
        "YBS 301 - Veri Tabanı ve Veri Tabanı Yönetim Sistemleri",
        "YBS 305 - Bilgisayar Donanım ve İşletim Sistemleri",
        "ISL 301 - Üretim Yönetimi",
        "YBS 303 - Bilişim Hukuku ve Etiği",
        "ISL 304 - Maliyet Muhasebesi",
        "YBS 309 - Sistem Analizi ve Tasarımı",
        "YBS 302 - Kurumsal Kaynak Planlama",
        "YBS 356 - Görsel Programlama",
        "YBS 358 - İnternet Programlama Dilleri",
        "YBS 366 - Mobil Programlama",
        "YBS 354 - Veri Madenciliği ve İş Zekası",
        "Proje Yönetimi",
      ],
      grade_4: [
        "YBS 401 - Bilişim Projeleri Yönetimi",
        "YBS 413 - Yapay Zeka",
        "YBS 421 - Makine Öğrenmesi",
        "YBS 425 - İş Analitiği Uygulamaları",
        "YBS 431 - Teknoloji ve İnovasyon Yönetimi",
        "YBS 441 - Python İle Web Veri Analizleri",
        "YBS 498 - Bitirme Çalışması",
        "YBS 402 - İşletmede Mesleki Eğitim",
        "ISL 495 - Kurumsal Yönetimde Dijital Dönüşüm",
      ],
    },
  },
  {
    id: 54,
    universite: "Bandırma Onyedi Eylül Üniversitesi",
    fakulte: "Ömer Seyfettin Uygulamalı Bilimler Fakültesi",
    fakulte_adresi:
      "Merkez Yerleşke, Yeni Mah. Şehit Astsubay Mehmetçik Cad. No:77, 10200 Bandırma/Balıkesir",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 55,
    universite: "Bursa Uludağ Üniversitesi",
    fakulte: "İnegöl İşletme Fakültesi",
    fakulte_adresi:
      "Cerrah Mah. Kalburt Mevkii, 4004. Sk. No:2, 16400 İnegöl/Bursa",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "IIZ1103 - İşletme",
        "IIZ1301 - Muhasebe I",
        "IUZ1101 - İktisat I",
        "IYZ1201 - Bilişim Sistemleri ve Teknolojilerine Giriş",
        "MAT1501 - Matematik I",
        "AIT101 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "TUD101 - Türk Dili I",
        "YAD101 - İngilizce I",
        "IIZ1302 - Muhasebe II",
        "IIZ1502 - Hukuka Giriş",
        "IUZ1102 - İktisat II",
        "IYZ1102 - Yönetim Bilimi",
        "IYZ1202 - Algoritma ve Programlamaya Giriş",
        "AIT102 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "TUD102 - Türk Dili II",
        "YAD102 - İngilizce II",
      ],
      grade_2: [
        "EKO2209 - İstatistik I",
        "IIZ2203 - E-Ticaret",
        "IYZ2105 - Modern Yönetim Teknikleri",
        "IYZ2203 - Nesne Yönelimli Programlama I",
        "EKO2210 - İstatistik II",
        "EKO2302 - Yöneylem Araştırması",
        "IYZ2202 - Yönetim Bilişim Sistemleri",
        "IYZ2204 - Nesne Yönelimli Programlama II",
        "IYZ2206 - Veritabanı Yönetim Sistemleri",
        "IYS2208 - Betik Diller (S)",
        "IYS2210 - Ağ Temelleri (S)",
      ],
      grade_3: [
        "IIZ3105 - İnsan Kaynakları Yönetimi",
        "IYZ3201 - Sistem Analiz ve Tasarımı",
        "IYZ3203 - Mobil Programlama",
        "IIZ3208 - Pazarlama",
        "IYZ3106 - Bilgi Toplumu ve E-Devlet",
        "IYZ3202 - Nesne Yönelimli Modelleme",
        "IYS3205 - Veri Yapıları ve Programlama (S)",
        "IYS3204 - Bilişim Güvenliği (S)",
        "IYS3212 - Kurumsal Kaynak Planlama Sistemleri (S)",
        "IYS3216 - Bilişim Hukuku ve Etiği (S)",
      ],
      grade_4: [
        "IYZ4201 - Proje Geliştirme I",
        "IYZ4203 - Web Tabanlı Programlama",
        "IYZ4205 - Veri Madenciliği",
        "IYZ4202 - Proje Geliştirme II",
        "IYZ4204 - Bilgisayar Ağları",
        "IYZ4206 - Karar Destek Sistemleri",
        "IIS4113 - İşyeri Uygulaması (S)",
        "IYS4207 - İleri Programlama (S)",
        "IYS4212 - Python Programlama (S)",
        "IIS4124 - Stratejik Yönetim (S)",
      ],
    },
  },
  {
    id: 56,
    universite: "Mudanya Üniversitesi",
    fakulte: "Sanat ve Sosyal Bilimler Fakültesi",
    fakulte_adresi: "Çağrışan Mah. 2026. Sk. No:2, 16960 Mudanya/Bursa",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: [...temelYBSDersleri],
  },
  {
    id: 57,
    universite: "Trakya Üniversitesi",
    fakulte: "Uygulamalı Bilimler Fakültesi",
    fakulte_adresi:
      "Ayşekadın Yerleşkesi, Talatpaşa Asfaltı, 22030 Merkez/Edirne",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "01YBS101 - BİLİŞİM SİSTEMLERİNE VE TEKNOLOJİYE GİRİŞ",
        "01YBS105 - TEMEL EKONOMİ",
        "01YBS107 - GENEL İŞLETME",
        "01YBS109 - İŞLETME MATEMATİĞİ I",
        "01ZAI101 - ZORUNLU ATATÜRK İLKELERİ VE İNKILAP TARİHİ I",
        "01ZTD101 - ZORUNLU TÜRK DİLİ I",
        "01ZYD101 - ZORUNLU YABANCI DİL I (İNG.)",
        "02YBS102 - YÖNETİM BİLİŞİM SİSTEMLERİNE GİRİŞ",
        "02YBS104 - YÖNETİM VE ORGANİZASYON",
        "02YBS106 - GENEL MUHASEBE",
        "02YBS108 - İŞLETME MATEMATİĞİ II",
        "02YBS110 - GRAFİK TASARIM VE ANİMASYON",
        "02ZAI102 - ZORUNLU ATATÜRK İLKELERİ VE İNKILAP TARİHİ II",
        "02ZTD102 - ZORUNLU TÜRK DİLİ II",
        "02ZYD102 - ZORUNLU YABANCI DİL II (İNG.)",
      ],
      grade_2: [
        "03YBS201 - BİLGİSAYAR İŞLETİM SİSTEMLERİ",
        "03YBS203 - TEMEL HUKUK",
        "03YBS205 - İSTATİSTİK I",
        "03YBS207 - VERİ YAPILARI",
        "03YBS209 - MALİYET MUHASEBESİ",
        "03YBS211 - ÖRGÜTSEL DAVRANIŞ",
        "03YBS213 - İNGİLİZCE I",
        "04YBS202 - PAZARLAMA İLKELERİ",
        "04YBS204 - VERİ TABANI YÖNETİM SİSTEMLERİ",
        "04YBS206 - NESNEYE YÖNELİK PROGRAMLAMA",
        "04YBS208 - BİLGİSAYAR AĞLARI VE GÜVENLİĞİ",
        "04YBS210 - İSTATİSTİK II",
        "04YBS212 - STRATEJİK YÖNETİM",
        "04YBS214 - İNGİLİZCE II",
      ],
      grade_3: [
        "05YBS301 - GÖRSEL PROGRAMLAMA",
        "05YBS303 - SİSTEM ANALİZİ VE TASARIMI",
        "05YBS305 - YÖNEYLEM ARAŞTIRMASI",
        "05YBS307 - MESLEKİ İNGİLİZCE I",
        "Bölüm Seçmelik I & II",
        "Üniversite Seçmelik I",
        "06YBS302 - PROJE YÖNETİMİ",
        "06YBS304 - ARAŞTIRMA YÖNTEMLERİ",
        "06YBS306 - İLETİŞİM TEKNİKLERİ",
        "06YBS308 - MESLEKİ İNGİLİZCE II",
        "Bölüm Seçmelik III & IV",
        "Üniversite Seçmelik II",
      ],
      grade_4: [
        "07YBS401 - PROJE I",
        "07YBS403 - AR-GE VE YENİLİK YÖNETİMİ",
        "07YBS405 - ÜRETİM YÖNETİMİ",
        "Bölüm Seçmelik V, VI & VII",
        "Üniversite Seçmelik III",
        "08YBS402 - PROJE II",
        "08YBS404 - KURUMSAL KAYNAK PLANLAMA",
        "08YBS406 - TEDARİK ZİNCİRİ VE LOJİSTİK",
        "Bölüm Seçmelik VIII, IX & X",
        "Üniversite Seçmelik IV",
      ],
    },
  },
  {
    id: 58,
    universite: "Bilecik Şeyh Edebali Üniversitesi",
    fakulte: "İktisadi ve İdari Bilimler Fakültesi",
    fakulte_adresi:
      "Gülümbe Kampüsü, İstanbul-Eskişehir Yolu, 11230 Merkez/Bilecik",
    bolum: "Yönetim Bilişim Sistemleri",
    dersler: {
      grade_1: [
        "ENG101 - İngilizce I",
        "IKT101 - Mikro İktisada Giriş",
        "İSL101 - İşletmeye Giriş",
        "İSL103 - Genel Muhasebe",
        "SBK107 - Hukukun Temel Kavramları",
        "TRK101 - Türk Dili I",
        "YBS101 - Temel Bilgi Teknolojileri",
        "ENG102 - İngilizce II",
        "İSL106 - İşletme Fonksiyonları",
        "İSL107 - Genel Matematik",
        "TRK102 - Türk Dili II",
        "YBS102 - Yönetim Bilişim Sistemleri",
        "YBS104 - Genel İletişim Bilgisi",
        "YBS106 - Veri ve Bilgi Yönetimi",
      ],
      grade_2: [
        "İSL204 - Yöneylem Araştırması",
        "İSL209 - İstatistik",
        "YBS201 - Sistem Analizi ve Tasarımı",
        "YBS203 - Algoritma ve Programlama",
        "İİBF YBS Mesleki Seçmeli I",
        "İSL203 - Yönetim ve Organizasyon",
        "YBS202 - Programlama",
        "YBS204 - Veri Yapıları",
        "YBS206 - Pazarlama ve Dijital Pazarlama Stratejileri",
        "İİBF YBS Mesleki Seçmeli II",
      ],
      grade_3: [
        "İSL304 - İnsan Kaynakları Yönetimi",
        "YBS301 - Veri Tabanı Yönetim Sistemleri",
        "YBS303 - Yapay Zeka",
        "YBS305 - Üretim Yönetim Sistemleri",
        "İİBF YBS Mesleki Seçmeli III",
        "İSL302 - Finansal Yönetim",
        "YBS302 - Kurumsal Kaynak Planlama",
        "YBS304 - E-Ticaret",
        "YBS306 - Yenilik Yönetimi",
        "İİBF YBS Mesleki Seçmeli IV",
      ],
      grade_4: [
        "ATA101 - Atatürk İlkeleri ve İnkılap Tarihi I",
        "YBS401 - Bilgisayar Ağları ve Güvenliği",
        "YBS403 - Dijital Çağda Müşteri İlişkileri Yönetimi",
        "İİBF YBS Mesleki Seçmeli V",
        "ATA102 - Atatürk İlkeleri ve İnkılap Tarihi II",
        "YBS402 - Dijital Girişimcilik",
        "YBS404 - Bilişimde Proje Yönetimi",
        "İİBF YBS Mesleki Seçmeli VI",
      ],
    },
  },
];
